### ISSUE TITLE
Group_by_day doesn't work on Postgres: PG::GroupingError: ERROR:  column "trackings.date" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by starrychloe** [ankane/groupdate#100]
`= line_chart @data.group_by_day(:date, format: 'yy-M-d').average(:measure)`

Showing C:/Users/Chloe/workspace/MyBestBody/app/views/trackings/new.haml where line #33 raised:

PG::GroupingError: ERROR:  column "trackings.date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...TERVAL '0 hour') AT TIME ZONE 'Etc/UTC'  ORDER BY "trackings...
                                                             ^
: SELECT AVG("trackings"."measure") AS average_measure, (DATE_TRUNC('day', (date::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC' AS day FROM "trackings" WHERE "trackings"."user_id" = $1 AND "trackings"."tracking_category_id" = $2 AND (date IS NOT NULL) GROUP BY (DATE_TRUNC('day', (date::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC'  ORDER BY "trackings"."date" ASC

However, `= line_chart @data.group(:date).average(:measure)` works.

```
mybestbody=# \d trackings
                                          Table "public.trackings"
        Column        |            Type             |                       Modifiers
----------------------+-----------------------------+--------------------------------------------------------
 id                   | integer                     | not null default nextval('trackings_id_seq'::regclass)
 tracking_category_id | integer                     |
 user_id              | integer                     |
 date                 | date                        |
 measure              | numeric                     |
```

PostgreSQL 9.4.4

**Comment by ankane** [comment]
Thanks @starrychloe, I'm able to reproduce in the tests. I'll look into it.

```ruby
User.order(:id).group(:created_at).count # works
User.order(:id).group_by_day(:created_at).count # throws error
```

**Comment by ankane** [comment]
My bad, both fail with PostgreSQL. You'll need to remove the order with `unscoped`.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by markphelps** [comment]
Just wanted to mention that if you use [unscoped](http://apidock.com/rails/ActiveRecord/Scoping/Default/ClassMethods/unscoped) it will remove ALL previously set scopes for your query, which may not be what you want. I had to use `.unscope(:order)` to get it to work correctly.

see: http://apidock.com/rails/ActiveRecord/Scoping/Default/ClassMethods/unscoped

**Comment by andreaslillebo** [comment]
I also experienced the same issue using default scopes:

```ruby
default_scope { order('created_at DESC') }
```

I removed this from my model and used

```ruby
MyModel.all.order('created_at DESC')
```
instead.

**Comment by afuno** [comment]
@ankane 

```
Post.all.group_by_day(:created_at)
#or
Post.unscope(:order).group_by_day(:created_at)
```

Doesn't work:

```
PG::GroupingError: ERROR:  column "posts.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "posts".* FROM "posts...
               ^
: SELECT "posts".* FROM "posts" WHERE ("posts"."created_at" IS NOT NULL) GROUP BY (DATE_TRUNC('day', ("posts"."created_at"::timestamptz) AT TIME ZONE 'Europe/Moscow')) AT TIME ZONE 'Europe/Moscow'
```

What is the problem?

**Comment by fatosmorina** [comment]
@afuno The first query does not work because you are using all columns of the table `Post` and grouping only by 1 column. 

This should work, as we aren't specifying any column explicitly in the `Select` clause of the query:

`Post.group_by_day(:created_at).count`

**Comment by kylefox** [comment]
I think there might be an underlying problem with this gem and Postgres beyond scoping issues:

```ruby
User.unscoped.group_by_month(:created_at)
```

results in 

```
User Load (0.5ms)
  SELECT  "users".* FROM "users"
  WHERE ("users"."created_at" IS NOT NULL)
  GROUP BY
    (DATE_TRUNC('month', ("users"."created_at"::timestamptz) AT TIME ZONE 'Etc/UTC'))
  AT TIME ZONE 'Etc/UTC' LIMIT $1  [["LIMIT", 11]]

Traceback (most recent call last):

ActiveRecord::StatementInvalid
  (PG::GroupingError: ERROR:  column "users.id" must appear in the GROUP BY clause
  or be used in an aggregate function)
```

Here are the versions of the tools I'm using:

* Gems:
  * groupdate (4.3.0)
  * rails (5.2.4.1)
  * pg (1.2.2)
* PostgreSQL 10.10
* ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

**Comment by ankane** [comment]
Replace `group_by_day` with `group` and you'll see a similar error. You need to specify a calculation method like `count`, or Active Record will run the query in the Rails console before it's complete.
