### ISSUE TITLE
When used with Rails, but without ActiveRecord dependency requires it

### ISSUE THREAD

**Issue by zdraganov** [ankane/groupdate#101]
Auto require of the ActiveRecord dependency is not perfect option, because some project using rails without ActiveRecord, will have it required and potentially this will cause issues,

My setup is Rails(3.2) + MongoId and I doesn't have any dependencies to ActiveRecord. But after installing the Gem my cucumber tests failed with:
```
      ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
      features/sign_in_sign_up/sign_up.feature:12:in `Then I should see different platform options'
```

Removing the `groupdate` codebase requiring `active_record` and it's `groupdate/active_record` extension worked for me.

Here is link to my branch:
https://github.com/zdraganov/groupdate/tree/mongoid-integration

**Comment by ankane** [comment]
Thanks for reporting @zdraganov - should be fixed on master.
