### ISSUE TITLE
Incorrect dates when grouping array on date field.

### ISSUE THREAD

**Issue by emilkarl** [ankane/groupdate#110]
This is strange on the same set of records it will set incorrect grouped date if set is array instead of activerelation?

`range = Date.today.beginning_of_week..Date.today.end_of_week``

**Correct:**
```Event.unscoped.where(event_date: range).all.group_by_day(:event_date).count```

   (0.7ms)  SELECT COUNT(*) AS count_all, (DATE_TRUNC('day', (event_date::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC' AS day FROM "events"  WHERE ("events"."event_date" BETWEEN '2016-02-08' AND '2016-02-14') AND (event_date IS NOT NULL) GROUP BY (DATE_TRUNC('day', (event_date::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC'
```=> {Mon, 08 Feb 2016 00:00:00 UTC +00:00=>5,
 Tue, 09 Feb 2016 00:00:00 UTC +00:00=>4,
 Wed, 10 Feb 2016 00:00:00 UTC +00:00=>3,
 Thu, 11 Feb 2016 00:00:00 UTC +00:00=>5,
 Fri, 12 Feb 2016 00:00:00 UTC +00:00=>5,
 Sat, 13 Feb 2016 00:00:00 UTC +00:00=>4,
 Sun, 14 Feb 2016 00:00:00 UTC +00:00=>5}```

**Incorrect:**
```Event.unscoped.where(event_date: range).all.to_a.group_by_day(&:event_date).map { |k,v| [k,v.count] }```

  Event Load (0.7ms)  SELECT "events".* FROM "events"  WHERE ("events"."event_date" BETWEEN '2016-02-08' AND '2016-02-14')
```=> [[Sun, 07 Feb 2016 00:00:00 UTC +00:00, 5],
 [Mon, 08 Feb 2016 00:00:00 UTC +00:00, 4],
 [Tue, 09 Feb 2016 00:00:00 UTC +00:00, 3],
 [Wed, 10 Feb 2016 00:00:00 UTC +00:00, 5],
 [Thu, 11 Feb 2016 00:00:00 UTC +00:00, 5],
 [Fri, 12 Feb 2016 00:00:00 UTC +00:00, 4],
 [Sat, 13 Feb 2016 00:00:00 UTC +00:00, 5]]```

**Comment by emilkarl** [comment]
This is where it goes bad: https://github.com/ankane/groupdate/blob/master/lib/groupdate/magic.rb#L271

**Comment by ankane** [comment]
Not sure I fully understand. Can you add a failing test case for it?

**Comment by emilkarl** [comment]
Hi, I see now that this is not very clear what I meant. But from what I can see ex Sat 13 i 4 records in the correct and 5 in the array version. And 14 is missing in the second.

I solved this but I cant remember how tho. Looks at my commits around this time I think it had something to do with the date format in the array version.

I think it was me and not groupdate. Closing this.
