### ISSUE TITLE
Sum of few columns

### ISSUE THREAD

**Issue by ilp416** [ankane/groupdate#113]
Is it possible to get sums of few different columns?
For example i have Order model with count and price. Now i perform next, and run mapping data as arrays:
```
pricing_data = Order.group_by_month(:date_acc).sum(:price)
counts_data = Order.group_by_month(:date_acc).sum(:count)
```
But i want to get this in one query:
`data_prices_and_counts = Order.group_by_month(:date_acc).select('sum(price), sum(count)')`

Thanks

**Comment by ankane** [comment]
Try [calculate-all](https://github.com/codesnik/calculate-all) for this, courtesy of @codesnik.
