### ISSUE TITLE
Values for day_start that are not whole numbers

### ISSUE THREAD

**Issue by sridharraman** [ankane/groupdate#116]
As the example in the documentation states, the query, `User.group_by_day(:created_at, day_start: 2).count`, returns grouped by day with each day starting from 2 AM.

Extending this, is it possible to group by days with each day starting at a non-whole time, e.g. 3:30 AM. I tried `day_start: 2.5`, but it didn't work.

Is there an existing option already? Or is there a plan?

Thanks.

**Comment by ankane** [comment]
Should be possible now.

**Comment by sridharraman** [comment]
Thanks @ankane.

One clarification - along with the grouping, can I get a handle on the set of objects as well? Is there any way do to that?

For example: if I were to do `User.group_by_day(:created_at, day_start: 2)`, will I be able to iterate through the different user sets based on the split groups?
