### ISSUE TITLE
Missing documentation for how keys are generated

### ISSUE THREAD

**Issue by moonshoes87** [ankane/groupdate#119]
It is unclear how the keys created by the group_by_period function are assigned.

With the below code, do I get messages created on the week that _starts_ on '2016-03-21 00:00:00 UTC', or that _ends_ on '2016-03-21 00:00:00 UTC'?

`message_hash = messages.group_by_week('created_at')`
`message_hash['2016-03-21 00:00:00 UTC']`

**Comment by moonshoes87** [comment]
The ambiguity is also partially because of using range.

`to = Date.new(2015, 3, 2)`
`from = to - 7.days`
`message_hash = messages.group_by_week('created_at', range: from..to)`

So, message_hash.keys gives me `[2015-02-23, 2015-03-01]`.  It appears that it is giving as keys the two Sundays that belong to weeks that overlap with that range of days.  It's a little confusing because it is unclear whether messages being grouped will necessarily fall within the provided range.

**Comment by ankane** [comment]
Keys are for the start of the range. The commit above adds this to the readme.
