### ISSUE TITLE
Invalid SQL syntax when using ROLLUP

### ISSUE THREAD

**Issue by patrickf3139** [ankane/groupdate#120]
I tried to do a `.group("field with ROLLUP")` (should translate to "GROUP BY field with ROLLUP") on my query before including .group_by_period and I got a  `ActiveRecord::StatementInvalid` error. Groupdate seems to be mistaking the entire string "field with ROLLUP" to be the field name because the select statement looks like "SELECT bfmonitors.name with ROLLUP AS bfmonitors_name_with_rollup..."

**Comment by ankane** [comment]
Rails [lacks support](http://stackoverflow.com/questions/33007596/does-rails-have-group-by-with-rollup-query) as well. As far as I can tell, there's not an easy way to support it until ActiveRecord does.

**Comment by patrickf3139** [comment]
Just tested that solution. You are right. ActiveRecord does not support it as well. Closing this.
