### ISSUE TITLE
Time Zones for filtered records

### ISSUE THREAD

**Issue by ma-hu** [ankane/groupdate#121]
Hi, 
there is a problem with time zones:
`<%= line_chart Booking.group_by_day(:start_at, time_zone: "Berlin").count %>`

works perfect, but:

`<%= line_chart @current_user.bookings.group_by_day(:start_at, time_zone: "Berlin").count %>`

throws an Error:
Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql

Is it only possible to use all records - not filtered?

**Comment by ankane** [comment]
That's odd.  Associations are supported.  Try the `debug_time_zone_support` branch and let me know what error comes back.

**Comment by ma-hu** [comment]
Sorry, I'm relatively new to rails and just used the groupdate gem in my gemfile for usage with chartkick.
How can I make use of the `debug_time_zone_support` branch to get the error descriptions?

**Comment by ankane** [comment]
@ma-hu in your Gemfile, do:

```ruby
gem "groupdate", github: "ankane/groupdate", branch: "debug_time_zone_support"
```

and `bundle install` again.

**Comment by ma-hu** [comment]
@ankane thank you for your hint.
For 
`<%= line_chart @current_user.bookings.group_by_day(:start_at, time_zone: "Berlin").count %>`
the error I am getting is
`undefined method `to_time' for #<Mysql::Time:2016-04-15 22:00:00>
Did you mean?  to_date`

**Comment by ankane** [comment]
Try updating the `mysql` gem if you can. The `master` branch should be fully compatible with the latest version `2.9.1` (all tests green).

**Comment by ma-hu** [comment]
I proved, that the Version of the mysl gem is 2.9.1, but still the error occurs: 

> undefined method `to_time' for Mysql::Time:2016-04-15 22:00:00 Did you mean? to_date

I do nothave any idea why, because inmy test case here, the data behind "Booking" and "@current_user.bookings" is exactly the same.

**Comment by ankane** [comment]
Was able to reproduce and fix on master. Thanks for all the help @ma-hu! 💯
