### ISSUE TITLE
Results are empty when timezone is 'Caracas'

### ISSUE THREAD

**Issue by Carlows** [ankane/groupdate#122]
I got bitten by this on this week, the 'Caracas' timezone changed from '-04:30' to '-04:00' recently, I don't know how they get handled, but I'm getting empty results with timezones for Venezuela:

```ruby
TimeEntry.group_by_day(:created_at, format: '%d %b', time_zone: 'America/Caracas').count
{"05 May"=>0, "06 May"=>0, "07 May"=>0, "08 May"=>0}

TimeEntry.group_by_day(:created_at, format: '%d %b', time_zone: 'Caracas').count
{"05 May"=>0, "06 May"=>0, "07 May"=>0, "08 May"=>0}

TimeEntry.group_by_day(:created_at, format: '%d %b', time_zone: 'UTC').count
{"05 May"=>2, "06 May"=>0, "07 May"=>0, "08 May"=>3}
```
This only happens to me when I deploy to heroku, It seems heroku has the time zones updated (with Caracas as -04:00 instead of -04:30)

**Comment by ankane** [comment]
Hi Carlos, thanks for reporting. Can you provide more details on versions - Groupdate, Rails, PostgreSQL/MySQL - and paste the query that's executed?

**Comment by Carlows** [comment]
I'm using Groupdate 2.5.2, Rails 4.2.5.1 and Postgresql 9.5.2. 

```ruby
SELECT COUNT(*) AS count_all, (DATE_TRUNC('day', (created_at::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'America/Caracas') + INTERVAL '0 hour') AT TIME ZONE 'America/Caracas' AS day FROM "time_entries" WHERE (created_at IS NOT NULL) GROUP BY (DATE_TRUNC('day', (created_at::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'America/Caracas') + INTERVAL '0 hour') AT TIME ZONE 'America/Caracas'
```

**Comment by ankane** [comment]
Thanks, can you paste the output of running the SQL directly against Postgres?

**Comment by Carlows** [comment]
This is the output:

```sql
billshl::DATABASE=> SELECT COUNT(*) AS count_all, (DATE_TRUNC('day', (created_at::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'America/Caracas') + INTERVAL '0 hour') AT TIME ZONE 'America/Caracas' AS day FROM "time_entries" WHERE (created_at IS NOT NULL) GROUP BY (DATE_TRUNC('day', (created_at::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'America/Caracas') + INTERVAL '0 hour') AT TIME ZONE 'America/Caracas';
 count_all |          day           
-----------+------------------------
         4 | 2016-05-06 04:30:00+00
        13 | 2016-05-05 04:30:00+00
         1 | 2016-05-04 04:30:00+00
         1 | 2016-05-08 04:30:00+00
         5 | 2016-05-03 04:30:00+00
(5 rows)
```
although that seems wrong, it's using 04:30 instead of 04:00

**Comment by Carlows** [comment]
How do these timezones get handled? I'm looking for a workaround for this, but I don't quite understand how the timezones from rake time:zones:all get set 😢

**Comment by ankane** [comment]
It looks like the database doesn't have the updated time zone offset. http://dba.stackexchange.com/questions/137235/postgresql-wont-take-new-timezone

If it's a Heroku hosted database, you may want to file a support ticket.

**Comment by Carlows** [comment]
Oh, thanks, that's actually the problem, the database has outdated timezones, I'm closing this as it has nothing to do with the gem.
