### ISSUE TITLE
group_by_day and sum returning data points for days with no data

### ISSUE THREAD

**Issue by cecomp64** [ankane/groupdate#123]
Hi,

I am hoping to use group_by_day and aggregate with sum, but when I do so, I get data points on days for which there is no data.  Here's an example.

Say my data is:

| Date | Number |
| ------ | -------------|
| May 7 | 3.0 |
| May 8 | 4.0 |
| May 8 | 4.0 |
| May 9 | 0.0 |
| May 14 | 4.0|

I then get the following from sum:

`> p.group_by_day(:date).sum(:magnitude)
 => {Sat, 07 May 2016 00:00:00 PDT -07:00=>3.0, 
Sun, 08 May 2016 00:00:00 PDT -07:00=>8.0, 
Mon, 09 May 2016 00:00:00 PDT -07:00=>0, 
Tue, 10 May 2016 00:00:00 PDT -07:00=>0, 
Wed, 11 May 2016 00:00:00 PDT -07:00=>0, 
Thu, 12 May 2016 00:00:00 PDT -07:00=>0, 
Fri, 13 May 2016 00:00:00 PDT -07:00=>0, 
Sat, 14 May 2016 00:00:00 PDT -07:00=>4.0}`

In the example above, the days with sums of 0 actually have no data points.  A data point of 0 is significant to me, so I only want to see it if that day actually has a data point, and the sum of that day's total is 0.  Count does the same thing.  

I would instead want to see this:

` {Sat, 07 May 2016 00:00:00 PDT -07:00=>3.0, 
Sun, 08 May 2016 00:00:00 PDT -07:00=>8.0, 
Mon, 09 May 2016 00:00:00 PDT -07:00=>0, 
Sat, 14 May 2016 00:00:00 PDT -07:00=>4.0}`

Any idea how I can do that with this library?  How do I remove all of those extra 0 data points?

**Comment by ankane** [comment]
Hey Carl, you can use the `default_value: nil` option, and then select the values that aren't nil, like:

```ruby
p.group_by_day(:date, default_value: nil).sum(:magnitude).reject { |_, v| v.nil? }
```

**Comment by cecomp64** [comment]
That does the trick - thanks for the quick reply!
