### ISSUE TITLE
nested relationship and unscoping issue

### ISSUE THREAD

**Issue by redsparklabs** [ankane/groupdate#125]
I have a nested relationship that I want to create a graph from.
Merchant has_many Divisions
Division has_many Promotions
Promotion has_many Scans

I want to create a graph of a single Merchants scans.

`@merchant.scans.group_by_week(:created_at, last: 26).count` 

won't work without unscoping, however when I unscope I lose my relationship to the merchant.  I get a graph of all scans for all merchants.

Any way around this other than removing all default scopes?

**Comment by ankane** [comment]
If it's an issue with ordering, you can use the reorder method to clear the ordering.

**Comment by redsparklabs** [comment]
I just removed all of the default scopes.  Probably best practice anyway.
