### ISSUE TITLE
group_by_day_of_week is off by a day?

### ISSUE THREAD

**Issue by thepiggod** [ankane/groupdate#126]
I am working on adding a graph to an existing ticket system, however the series/hash returned seems to always be off by one day.

`Ticket.group_by_day_of_week(:created_at, format: "%a", range: Date.today.years_ago(2).all_week).count`

in rails console returns:

`{"Sun"=>36, "Mon"=>29, "Tue"=>34, "Wed"=>28, "Thu"=>47, "Fri"=>0, "Sat"=>0}`

This ticketing system rarely sees use on weekends, so the hash SHOULD have been like:

`{"Mon"=>36, "Tue"=>29, "Wed"=>34, "Thu"=>28, "Fri"=>47, "Sat"=>0, "Sun"=>0}`

but the root cause seems to be the SQL generated by the day_of_week method:

`SELECT COUNT(*) AS count_all, DAYOFWEEK(CONVERT_TZ(DATE_SUB(created_at, INTERVAL 0 HOUR), '+00:00', 'America/Los_Angeles')) - 1 AS day_of_week FROM`tickets`WHERE (created_at >= '2014-05-19' AND created_at <= '2014-05-25') GROUP BY DAYOFWEEK(CONVERT_TZ(DATE_SUB(created_at, INTERVAL 0 HOUR), '+00:00', 'America/Los_Angeles')) - 1`

If I run this query manually WITHOUT the "- 1" after the DAYOFWEEK calls, I get a correct result (where sunday=0)

So why is that "- 1" being added to the query?

**Comment by ankane** [comment]
Hey @thepiggod, I just looked at the tests and found one issue with enumerables and the `week_start` option, but didn't see anything else odd. Can you add a failing test case for it?

**Comment by ankane** [comment]
The reason for -1 is that `DAYOFWEEK` returns numbers 1-7 (1 being Sunday), and we want Sunday to be 0.

**Comment by bh13731** [comment]
😔

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen with more info.
