### ISSUE TITLE
Supported aggregation methods (sum/min/max/count)?

### ISSUE THREAD

**Issue by alexkrolick** [ankane/groupdate#127]
I'm getting a `TypeError: no implicit conversion of Symbol into Integer` when I try `Thing.group_by_day(:date).min(:value)`. I thought all of the Active Record aggregation methods would be supported but it seems like only `count` and `sum` are successful. Is that a bug or intentional, or an issue with my database?

**Comment by ankane** [comment]
Try `minimum` instead of `min`.

**Comment by alexkrolick** [comment]
http://guides.rubyonrails.org/active_record_querying.html#minimum

Thank you, that is right.
