### ISSUE TITLE
group_by_year performance in PG

### ISSUE THREAD

**Issue by jalberto** [ankane/groupdate#130]
I am having some perfoemance problems using group_by_year in PG.

The table contains 6506 items when I do:

    Model.group_by_year(:doc_date, format: '%Y').count

It takes 'forever' (15mins and counting). This is the SQL generated:

    SELECT COUNT(*) AS count_all, (DATE_TRUNC('year', (doc_date::timestamptz - INTERVAL '0 second') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 second') AT TIME ZONE 'Etc/UTC' AS date_trunc_year_doc_date_timestamptz_interval_0_second_at_time_ FROM "models" WHERE (doc_date IS NOT NULL) GROUP BY (DATE_TRUNC('year', (doc_date::timestamptz - INTERVAL '0 second') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 second') AT TIME ZONE 'Etc/UTC'

Maybe I am using groupdate wrongly?

Regards

**Comment by ankane** [comment]
Hi @jalberto, the query looks right.  Groupdate can group millions of items in under 30 seconds with the right hardware.  You may need more resources (CPU, memory, etc) for your DB..

**Comment by jalberto** [comment]
it's actuallly a baremetal server with 32gb of ram adn SSD.

If I do a simpler SQL statement with interval is mostly instant

**Comment by ankane** [comment]
I'm not sure what it'd be in that case.

**Comment by jalberto** [comment]
Is quite weird, with ~6k tiems is ok, but after ~12k becomes very slow. I suspect is related to the timezone calculation per tiem.

Is there any option to forget about timezonse when doing the grouping? when grouping by year, timezone makes not too much sense

**Comment by ankane** [comment]
Very odd, seems like there's a performance bottleneck somewhere.

Time zones still apply to grouping by year, but If you don't need them, you can use date_trunc directly.

**Comment by elsurudo** [comment]
@jalberto I am having what seems to be a similar issue (https://github.com/ankane/groupdate/issues/135). Could you check to see whether the query finishes quickly if you run the SQL directly on the DB? In my case, SQL is not the bottleneck – I am wondering if it is the same in your case.

**Comment by jalberto** [comment]
@elsurudo @ankane is not instant, but at least it finish, running it on groupdate hangup. Maybe same loop problem?

**Comment by elsurudo** [comment]
@jalberto Thanks for the reply, but @ankane solved the issue I was having already (which was indeed an infinite loop problem). So yours must be a different issue.

**Comment by ankane** [comment]
Cleaning up issues.  @jalberto let me know if you find anything new.
