### ISSUE TITLE
Arrays and Hashes - what do they do?

### ISSUE THREAD

**Issue by btrscott** [ankane/groupdate#136]
Could be a documentation issue or a dumb user issue but.... I have no idea what "Array and Hashes" in the documentation is trying to do?

Are they filtering the list?  (I would like to run simple select or reject blocks on the group_by before we do a count.  I would also like to do groupings.

Example - I have a group of time punches by employees over many days.
Go through a list of time punches, select those that match a particular warehouse and total those up.
Filter out time punches to those with a department of 'x'.

Best case to to use groupdate to give me a hash of warehouses -> departments -> count

Sometimes I need to filter the departments with a block like warehouses -> departments starting with 'S' -> count.

Can groupdate do any of this?  Is that what the documentation is referring to?

**Comment by ankane** [comment]
Hey @btrscott, try the examples in the readme to see how they behave.
