### ISSUE TITLE
unique_count

### ISSUE THREAD

**Issue by sposinff** [ankane/groupdate#137]
I just discovered chartkick and groupdate today.  Great stuff!

I am wondering if it is possible to go a level deeper into the data to get a unique count.  For instance, if I am trying to get the number of visits to a site I could do
```Visitor.group_by_day(:visited_at, last: 30).count```
But what if a visitor could more than once on a day?  How can I get unique visitors for each day?

Thank you.

**Comment by ankane** [comment]
Hey Stuart, glad you're finding the projects useful.  Check out ActiveRecord's `distinct` method to see how to accomplish this.

**Comment by sposinff** [comment]
I have tried with distinct before and after group_by_day but the results are the same, as if the distinct is not even there. I get the same results for all three of these.

```
Visitor.group_by_day(:visited_at, last: 30).count
Visitor.distinct(:visitor_id).group_by_day(:visited_at, last: 30).count
Visitor.group_by_day(:visited_at, last: 30).distinct(:visitor_id).count
```

I am sure I am missing something.  Your help is appreciated.

**Comment by sposinff** [comment]
I am missing the select.  Got it now.  Thanks again.

**Comment by drewbaumann** [comment]
> Yep, I am able to use `.select(:visitor_id).distinct`. Thank you.

@sposin I know this is old, but what did your query end up looking like? I do not see this working as expected.

**Comment by bbugh** [comment]
@drewbaumann this is a bit late, but maybe will still help you or others. For example, if you wanted the count of unique users who created an ahoy event by month:

```ruby
Ahoy::Event.select(:user_id).distinct.group_by_month(:time).count
```

<details>
<summary>The resulting SQL query</summary>

```sql
SELECT
  COUNT(DISTINCT "ahoy_events"."user_id") AS count_user_id,
  (
    DATE_TRUNC(
      'month',
      (time :: timestamptz) AT TIME ZONE 'Etc/UTC'
    )
  ) AT TIME ZONE 'Etc/UTC' AS date_trunc_month_time_timestamptz_at_time_zone_etc_utc_at_time_
FROM
  "ahoy_events"
WHERE
  (time IS NOT NULL)
GROUP BY
  (
    DATE_TRUNC(
      'month',
      (time :: timestamptz) AT TIME ZONE 'Etc/UTC'
    )
  ) AT TIME ZONE 'Etc/UTC'
```
</details>
