### ISSUE TITLE
group_by_period is not working as intended

### ISSUE THREAD

**Issue by bodrovis** [ankane/groupdate#139]
Good day! Following our quick discussion via e-mail I'm opening an issue here. The idea is that I can't get the `group_by_period` method working. Here https://github.com/bodrovis/Sitepoint-source/blob/master/Graphs_Chartkick_Practice/app/controllers/api/click_tracks_controller.rb#L9 I have a somewhat ugly solution to call the right method to group my data.

The `@click_tracks` is defined here https://github.com/bodrovis/Sitepoint-source/blob/master/Graphs_Chartkick_Practice/app/controllers/api/base_controller.rb#L9 

I try:

```ruby
@click_tracks.group_by_period(:day, :created_at).count
```

and get

```
TypeError: no implicit conversion of Symbol into Integer
from F:/Ruby223/lib/ruby/gems/2.2.0/gems/groupdate-3.0.1/lib/groupdate/enumerable.rb:16:in `[]'
```

Using

```ruby
@click_tracks.group_by_period(:day, :created_at, format: '%d %b').count
```

returns

```
ArgumentError: wrong number of arguments (3 for 1..2)
from F:/Ruby223/lib/ruby/gems/2.2.0/gems/groupdate-3.0.1/lib/groupdate/enumerable.rb:14:in `group_by_period'
```

Not sure what I'm doing wrong here. Any help is much appreciated. Could it be because `@click_tracks` is a collection fetched from one-to-many association?..

**Comment by bodrovis** [comment]
To reproduce this issue you may clone the app and insert `binding.pry` here https://github.com/bodrovis/Sitepoint-source/blob/master/Graphs_Chartkick_Practice/app/controllers/api/click_tracks_controller.rb#L9 to stop the code execution at that point

**Comment by ankane** [comment]
Looks like you found a bug with `group_by_period` and associations :) Should be fixed on master.

**Comment by bodrovis** [comment]
Oh, great!
