### ISSUE TITLE
[feature request] Filter by subgroups per time unit

### ISSUE THREAD

**Issue by tunamonster** [ankane/groupdate#153]
I like to use groupdate to visualize time series data, but when I want to go beyond the basic use case of showing a single value per model per time unit, I need to write several loops to split the data, iteratively apply groupdate's methods, and recombine the data to return a single hash. 

My frequent use cases for this are date adjustable pie charts and stacked column charts.

To generate this data easier and faster, I would like to submit a PR to create a function to pass an attribute to filter the date counts by.

For example, `Model.group_by_day(:created_at).filter_by(:group_id).count` would return:

```
Hash => {
                  day1 => {group1 => g1d1.count, group2 => g2d1.count, ...}, 
                  day2=> {group1 => g1d2.count, ..., groupm => gmd2.count}, 
                  ..., 
                 dayn => {...} 
               }
```

Would you consider this feature a welcome addition to the gem?

**Comment by ankane** [comment]
Hey @tunamonster, it looks like you want to group by day and group id. You should be able to do:

```ruby
Model.group(:group_id).group_by_day(:created_at).count
```

**Comment by tunamonster** [comment]
Thanks, it changes the data structure, but does the same job!
