### ISSUE TITLE
Multiple groups and no data

### ISSUE THREAD

**Issue by randy-girard** [ankane/groupdate#157]
I have looked through the issues and docs and it appears this should work, so maybe im doing something wrong, but if i use a `group` in addition to the `group_by_*` and there doesn't happen to be any data during that range of time, then I get an empty hash back. Is this expected?

Note: I am left joining a table, so I should still get the left data set and just nulls on the right.

**Comment by ankane** [comment]
Yeah, if you have another group clause and there is no data, it doesn't make sense to return anything.

**Comment by randy-girard** [comment]
I can see both sides. In my case, I have a need to still get the group by timegroup by calculation even if there is no data. In the case of left joins, the group should still be present whether there is data on the right or not.

**Comment by ankane** [comment]
Not sure I follow. Feel free to add code to reproduce.
