### ISSUE TITLE
Be sure to install time zone support

### ISSUE THREAD

**Issue by hoantv** [ankane/groupdate#158]
I had already installed "MySQL Server Time Zone Support"
![image](https://cloud.githubusercontent.com/assets/95798/21755834/f955d616-d64b-11e6-9003-267d9c96e20e.png)
![image](https://cloud.githubusercontent.com/assets/95798/21755847/1620ae92-d64c-11e6-8ddc-b30945862553.png)
But i faced to this problem:
![image](https://cloud.githubusercontent.com/assets/95798/21755857/2585403c-d64c-11e6-89f4-6c06969c3c77.png)

**Comment by ankane** [comment]
Try the `debug_time_zone_support` branch. See #121 for detailed instructions.

**Comment by hoantv** [comment]
When i add 


F:\Project\ProblemManagementSystem>bundle install
Resolving dependencies...
Using rake 11.2.2
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.1
Using execjs 2.7.0
Using htmlentities 4.3.4
Using rubyzip 1.1.7
Using bcrypt 3.1.11
Using debug_inspector 0.0.2
Using method_source 0.8.2
Using thor 0.19.1
Using sass 3.4.22
Using bootstrap-table-rails 1.11.0
Using bundler 1.12.5
Using byebug 9.0.5
Using tilt 2.0.5
Using chartkick 2.2.1
Using coffee-script-source 1.8.0
Using daemons 1.2.3
Using eventmachine 1.2.0.1
Using multi_json 1.12.1
Using json 1.8.3
Using magnific-popup-rails 1.1.0
Using mimemagic 0.3.2
Using mysql2 0.4.4
Using rails-assets-tether 1.3.3
Using rufus-scheduler 3.2.1
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using sprockets 3.7.0
Using websocket-driver 0.6.4
Using mime-types 3.1
Using autoprefixer-rails 6.3.7
Using uglifier 3.0.1
Using binding_of_caller 0.7.2
Using coffee-script 2.4.1
Using thin 1.7.0
Using rdoc 4.2.2
Using turbolinks 5.0.1
Using activesupport 5.0.0.1
Using tzinfo-data 1.2016.6
Using loofah 2.0.3
Using axlsx 2.1.0.pre
Using caracal 1.0.6
Using roo 2.4.0
Using rubyXL 3.3.21
Using mail 2.6.4
Using bootstrap-sass 3.3.7
Using sdoc 0.4.1
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0.1
Using climate_control 0.0.3
Using jbuilder 2.6.0
Using pundit 1.1.0
Using rails-html-sanitizer 1.0.3
Using activejob 5.0.0.1
Using activerecord 5.0.0.1
Using cocaine 0.5.8
Using actionview 5.0.0.1
Using ancestry 2.1.0
Using hightop 0.1.4
Using paperclip 5.0.0
Using actionpack 5.0.0.1
Using actioncable 5.0.0.1
Using actionmailer 5.0.0.1
Using axlsx_rails 0.5.0
Using railties 5.0.0.1
Using sprockets-rails 3.1.1
Using bootstrap-datepicker-rails 1.6.1.1
Using coffee-rails 4.1.1
Using font-awesome-rails 4.6.3.1
Using jquery-rails 4.1.1
Using rails 5.0.0.1
Using sass-rails 5.0.6
Using web-console 2.3.0
Using wysiwyg-rails 2.3.4
Using caracal-rails 1.0.1
Using chosen-rails 1.5.2
Bundle complete! 36 Gemfile dependencies, 91 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

F:\Project\ProblemManagementSystem>bundle install
Fetching git://github.com/ankane/groupdate.git
Retrying git clone "git://github.com/ankane/groupdate.git" "C:/Ruby22-x64/lib/ru
by/gems/2.2.0/cache/bundler/git/groupdate-da0117ce4d41244e2f6dd9eb0e33e407492816
a1" --bare --no-hardlinks --quiet due to error (2/4): Errno::ENOENT No such file
 or directory - git clone "git://github.com/ankane/groupdate.git" "C:/Ruby22-x64
/lib/ruby/gems/2.2.0/cache/bundler/git/groupdate-da0117ce4d41244e2f6dd9eb0e33e40
7492816a1" --bare --no-hardlinks --quiet
Retrying git clone "git://github.com/ankane/groupdate.git" "C:/Ruby22-x64/lib/ru
by/gems/2.2.0/cache/bundler/git/groupdate-da0117ce4d41244e2f6dd9eb0e33e407492816
a1" --bare --no-hardlinks --quiet due to error (3/4): Errno::ENOENT No such file
 or directory - git clone "git://github.com/ankane/groupdate.git" "C:/Ruby22-x64
/lib/ruby/gems/2.2.0/cache/bundler/git/groupdate-da0117ce4d41244e2f6dd9eb0e33e40
7492816a1" --bare --no-hardlinks --quiet
Retrying git clone "git://github.com/ankane/groupdate.git" "C:/Ruby22-x64/lib/ru
by/gems/2.2.0/cache/bundler/git/groupdate-da0117ce4d41244e2f6dd9eb0e33e407492816
a1" --bare --no-hardlinks --quiet due to error (4/4): Errno::ENOENT No such file
 or directory - git clone "git://github.com/ankane/groupdate.git" "C:/Ruby22-x64
/lib/ruby/gems/2.2.0/cache/bundler/git/groupdate-da0117ce4d41244e2f6dd9eb0e33e40
7492816a1" --bare --no-hardlinks --quiet
--- ERROR REPORT TEMPLATE ------------------------------------------------------
-
- What did you do?

  I ran the command `C:/Ruby22-x64/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::ENOENT: No such file or directory - git clone "git://github.com/ankan
e/groupdate.git" "C:/Ruby22-x64/lib/ruby/gems/2.2.0/cache/bundler/git/groupdate-
da0117ce4d41244e2f6dd9eb0e33e407492816a1" --bare --no-hardlinks --quiet
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/g
it/git_proxy.rb:149:in ``'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/g
it/git_proxy.rb:149:in `block in git'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/shared_h
elpers.rb:72:in `call'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/shared_h
elpers.rb:72:in `with_clean_git_env'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/g
it/git_proxy.rb:149:in `git'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/g
it/git_proxy.rb:143:in `block in git_retry'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/retry.rb
:39:in `call'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/retry.rb
:39:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/retry.rb
:29:in `attempt'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/g
it/git_proxy.rb:142:in `git_retry'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/g
it/git_proxy.rb:98:in `checkout'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/g
it.rb:154:in `specs'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definiti
on.rb:556:in `block in converge_locked_specs'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definiti
on.rb:545:in `each'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definiti
on.rb:545:in `converge_locked_specs'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definiti
on.rb:195:in `resolve'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definiti
on.rb:140:in `specs'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definiti
on.rb:129:in `resolve_remotely!'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installe
r.rb:195:in `resolve_if_need'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installe
r.rb:70:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installe
r.rb:22:in `install'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/inst
all.rb:102:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:1
75:in `install'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/t
hor/lib/thor/command.rb:27:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/t
hor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/t
hor/lib/thor.rb:359:in `dispatch'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/t
hor/lib/thor/base.rb:440:in `start'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:1
1:in `start'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `bl
ock in <top (required)>'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly
_errors.rb:98:in `with_friendly_errors'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<t
op (required)>'
      C:/Ruby22-x64/bin/bundle:23:in `load'
      C:/Ruby22-x64/bin/bundle:23:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  2.4.5.1
  Ruby      2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
  GEM_HOME  C:/Ruby22-x64/lib/ruby/gems/2.2.0
  GEM_PATH  C:/Ruby22-x64/lib/ruby/gems/2.2.0;C:/Users/hoantv/.gem
/ruby/2.2.0
  Git       not installed
--- TEMPLATE END ---------------------------------------------------------------
-

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this err
or:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clon
e+%22git%3A%2F%2Fgithub.com%2Fankane%2Fgroupdate.git%22+%22C%3A%2FRuby22-x64%2Fl
ib%2Fruby%2Fgems%2F2.2.0%2Fcache%2Fbundler%2Fgit%2Fgroupdate-da0117ce4d41244e2f6
dd9eb0e33e407492816a1%22+--bare+--no-hardlinks+--quiet&type=Issues

If there aren't any reports for this error yet, please create copy and paste the
 report template above into a new issue. Don't forget to anonymize any private d
ata! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

F:\Project\ProblemManagementSystem>

**Comment by ankane** [comment]
Try running on your server:

```sql
SELECT CONVERT_TZ(NOW(), '+00:00', 'Etc/UTC');
```

If it returns `NULL`, time zone support is not enabled.

**Comment by hoantv** [comment]
Thank Ankane,
 after i reconfigured "MySQL Server Time Zone Support", problem was solved.
