### ISSUE TITLE
Single arbitrary range result?

### ISSUE THREAD

**Issue by philsmy** [ankane/groupdate#159]
I'm not sure how to search to see if this is possible, but, I want to group by the last 30 days and get a single result. eg:
`Class.group_by_range(:run_at,range: 30.days.ago..Time.now).count`

and have a single results come in like `{range => 12345}`

Grouping by anything else seems to return multiple key/value pairs. (Even, at the moment, group by year as we've just changed years).

**Comment by ankane** [comment]
Hey @philsmy, you should be able to do this without Groupdate.

```ruby
Class.where("run_at > ? and run_at < ?", 30.days.ago, Time.now).count
```
