### ISSUE TITLE
Week start Monday produces error

### ISSUE THREAD

**Issue by tangopium** [ankane/groupdate#164]
If I use `Groupdate.week_start = :mon` or `User.group_by_week(:created_at, week_start: :mon)` I get the error `Be sure to install time zone support`. I do actually have the support installed. The weird thing here is, that it just happens with `:mon`, with no day else. Any help?

**Comment by ankane** [comment]
Hey @tangopium, not sure what it could be. A few questions:

1. What version of the gem are you on? (check in your Gemfile.lock or run `puts Groupdate::VERSION`)
2. What does this output?

```sql
SELECT CONVERT_TZ(NOW(), '+00:00', 'Etc/UTC');
```

**Comment by tangopium** [comment]
Hey :) I'm using version 3.1.1 and the output of the Mysql command was `2017-04-10 08:23:38`

**Comment by tangopium** [comment]
Wow! That's weird: the error just disappeared. I restarted everything yesterday and it didnt't help. Maybe some cache issue. Sorry for the inconvenience!

**Comment by ankane** [comment]
Glad it's working 👍
