### ISSUE TITLE
why you are not use self.time_zone.formatted_offset  replace self.time_zone.tzinfo.name

### ISSUE THREAD

**Issue by houdl** [ankane/groupdate#165]
why you are not use self.time_zone.formatted_offset  replace self.time_zone.tzinfo.name,
then groupdate will not dependent on Time zone support for mysql

**Comment by ankane** [comment]
Hey @houdl, for time zones with daylight saving time, the offset changes depending on the time of year. If you have a table with two records - one in July and one in December - and group by Pacific Time, they need different offsets.

That's why MySQL has time zone support to begin with :)

**Comment by houdl** [comment]
@ankane  ok, thanks, awesome!
