### ISSUE TITLE
return relation what have count and time will be better.

### ISSUE THREAD

**Issue by houdl** [ankane/groupdate#167]
in this gem, finally will use 
```ruby
Model.group(xxx).count
```
It will return a hash, i think it will be better, if it use
```ruby
Model.select("").group(xxx)
```
it will return a relation, and select more fileds, and get more infomation.
So will you add this function?

**Comment by ankane** [comment]
Hey @houdl, are you looking for something like https://github.com/codesnik/calculate-all?

**Comment by houdl** [comment]
thanks, it is awesome to combine calculate-all with groupdate.
