### ISSUE TITLE
How to add `group_by_year` column to select?

### ISSUE THREAD

**Issue by dzjuck** [ankane/groupdate#168]
I have a query with `group_by_year` where i'm changing selected columns:

```ruby
Attendance.
  joins(:student => :school).
  select("ARRAY_AGG(students.id) AS students").
  where(:students => { :school_id => 1}).
  group_by_year('attendances.created_at').
  order("count(*) DESC")
```

A result rows does not contain `group_by_year`. I can't find how to get generated `group_by_year` expression to use in `select`. I thought about something like this:

```ruby
field = Attendance.group_by_year_column(:created_at)
...
select("#{field}, ...")
```

**Comment by ankane** [comment]
Hey @dzjuck, you need to use something like [calculate-all](https://github.com/codesnik/calculate-all) for this.
