### ISSUE TITLE
Group by month and time zones

### ISSUE THREAD

**Issue by airblade** [ankane/groupdate#169]
Hello!

I have code like this:

```ruby
months = Credit.group_by_month(:published_on, dates: true, series: false).reverse_order.keys
```

Only 1 row in the `credits` table has a `published_on` datetime, and its value is 15 May 2017.

However when I run the code and inspect `months` I see: `2017-04-30 23:00:00 UTC`.  I would expect to see something like `2017-05-01 00:00:00 UTC`.

My Rails app hasn't configured a time zone so it should be using UTC.  My laptop is on British Summer Time which is currently 1 hour ahead of UTC.

I have the same problem whether I'm viewing the development site or the production site (whose server uses UTC).

Please could you tell me what I'm doing wrong?

Also, the `dates` option doesn't seem to make any difference.  Is that expected?

I'm using Groupdate 2.5.3, Rails 3.2.22.4, Ruby 2.1.3.

Thanks!

**Comment by ankane** [comment]
Hey @airblade, try upgrading to the latest version of Groupdate.

**Comment by airblade** [comment]
That fixed it.

Not sure why I didn't try upgrading in the first place ;)

Thanks!
