### ISSUE TITLE
Rails 5 deprecation warning

### ISSUE THREAD

**Issue by giuseb** [ankane/groupdate#172]
In Rails 5, `alias_method_chain` has been deprecated, hence `groupdate` raises a warning. Any chances that this may be fixed? Thanks!

**Comment by ankane** [comment]
Hey @giuseb, what version of Groupdate are you on?

**Comment by giuseb** [comment]
3.2.0

the deprecated method is called twice from `/lib/groupdate/active_record.rb`

cheers
Giuseppe

**Comment by ankane** [comment]
Yeah, both have conditionals.

https://github.com/ankane/groupdate/blob/a3cd9f99a3b5cdabdccb43316f22f65a8dbba1fc/lib/groupdate/active_record.rb#L11

https://github.com/ankane/groupdate/blob/a3cd9f99a3b5cdabdccb43316f22f65a8dbba1fc/lib/groupdate/active_record.rb#L42
