### ISSUE TITLE
[Error] User.group_by_day(:created_at).count

### ISSUE THREAD

**Issue by fifiteen82726** [ankane/groupdate#176]
> Gem_version: 3.2.0
OS: OSX 10.12
MySQL version:  5.6.36

Here is some wired thing I've encountered.

This fails

```rb
User.group_by_day(:created_at).count

Groupdate::Error: Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql
from /Users/Coda/.rvm/gems/ruby-2.3.3@rails4271/gems/groupdate-3.2.0/lib/groupdate/magic.rb:186:in `perform'
```
However, this works.

```rb
 User.where('login_streak > 10').group_by_day(:created_at).count

{
    Thu, 16 Oct 2014 => 1,
    Fri, 17 Oct 2014 => 8,
    Sat, 18 Oct 2014 => 0,
    Sun, 19 Oct 2014 => 0,
...
}
```

This works, too

```rb
 User.group_by_day(:created_at)
```

I did run the command `mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql` in terminal, and I pass the test

``` sql
SELECT CONVERT_TZ(NOW(), '+00:00', 'Etc/UTC');

-- 2017-06-07 14:17:22
```

**Comment by ankane** [comment]
Hey @fifiteen82726, thanks for reporting 👍  Unfortunately, I'm not sure how to reproduce. If you can create a script to reproduce with a fresh database, that'd be great.

**Comment by crondaemon** [comment]
What I've found so far is that it applies to autogenerated scaffold fields (timestamps). They are created_at and updated_at. `created_at` doesn't work, `updated_at` works.

Reproducer: create a scaffold, and run

```
MyScaffold.group_by_day(:updated_at).count
MyScaffold.group_by_day(:created_at).count
```

Hope it helps.

**Comment by ankane** [comment]
Hey @crondaemon, for the case that isn't working (`created_at` I believe), can you run the SQL Groupdate generates manually to see what it returns?

**Comment by crondaemon** [comment]
ATM I can't reproduce it. Both the commands I posted work on my devel db. I need to recap on the issue to find out what the point was.

**Comment by nicholaskim94** [comment]
I've experienced this issue when the object in question has :created_at attribute of `nil` or `0000-00-00 00:00:00` in the database

```magic.rb
# groupdate/magic.rb:186
missing_time_zone_support = multiple_groups ? (result.keys.first && result.keys.first[@group_index].nil?) : result.key?(nil)
if missing_time_zone_support
  raise Groupdate::Error, "Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql"
end
```
I guess this behavior is intentional to check for timezone support, but maybe it would be helpful to point out this fact in the error message? 🤔
