### ISSUE TITLE
week_start: :today

### ISSUE THREAD

**Issue by sunnyrjuneja** [ankane/groupdate#178]
Hey Andrew,

Thanks for your excellent library! It's been incredibly helpful :smiley:.

I was wondering if you would accept a PR a new argument for week_start. Right now, week_start accepts a three letter symbol indicating the day (:sun, :mon, :tue, etc). For my purposes, I'm grouping using Next 7 days, 14 days, 21 days... (rather this week, next week, following week etc). The changing time horizon forces me to do something like `Date.today.wday` and matching to a symbol table.

If you're not happy with that solution, would you consider allowing week_start accept an integer following the same convention as [wday](https://ruby-doc.org/stdlib-2.4.1/libdoc/date/rdoc/Date.html#method-i-wday) (returns 0-6, where 0 is Sunday).

**Comment by ankane** [comment]
Hey @sunnyrjuneja, thanks for the suggestion. This doesn't seem like a popular use case, so I have reservations about supporting new arguments. You should be able to do:

```ruby
week_start = [:sun, :mon, :tue, :wed, :thu, :fri, :sat][Date.today.wday]
```

**Comment by sunnyrjuneja** [comment]
@ankane Totally reasonable, thanks for your consideration (and code snippet). I'll close the issue. Perhaps if more people chime in, we can re-open it.
