### ISSUE TITLE
Using with a loop

### ISSUE THREAD

**Issue by bassman88** [ankane/groupdate#180]
I'm trying to use group_by_month with a loop, I want to change the value from just a .count to an actual computation which is stored in the variable 'average' (as seen below):

SalesOrder.group_by_month(:created_at, format: "%b").each do |month|
    	average = (month.total_before_discount - month.discount_value) / month.total_lm
end

**Comment by ankane** [comment]
Hey @bassman88, I'd try the calculate-all gem: https://github.com/codesnik/calculate-all
