### ISSUE TITLE
Arbitrary results in controller and view

### ISSUE THREAD

**Issue by hundsim** [ankane/groupdate#182]
Environment:
Rails 5.1.4
Postgres 9.6.2

U'm querying around 2000 records with the following :

    Event.where.not(user_id: [1, 3, 290, 339]).group_by_week(:created_at, week_start: :mon, last: 13, reverse: true).count

Running this in the console gives the same result every time, but in the controller and the view the weekly count has a diff of 1-5 records.

Any clues what the reason of this is?

**Comment by ankane** [comment]
Hey @hundsim, that seems very odd. Are the SQL queries the same in the logs?

**Comment by hundsim** [comment]
OK, so the SQL queries are not the same. Appearantly the time zones are changing. 

I guess this issue has nothing at all to do with `groupdate`, so feel free to close the issue. But I will provide some information anyway if there's any clue whatsoever what's going here.

Nowhere in this request am I setting the the application's time zone to some new value. What I have in the application config is `config.time_zone = "UTC"`. And these is how two of the SQL looks like:


    SELECT COUNT(*) AS count_all, (DATE_TRUNC('week', (created_at::timestamptz - INTERVAL '0 day' - INTERVAL '0 second') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 day' + INTERVAL '0 second') AT TIME ZONE 'Etc/UTC' AS date_trunc_week_created_at_timestamptz_interval_0_day_interval_ FROM "events" WHERE ("events"."user_id" NOT IN (1, 3, 290, 339)) AND (created_at >= '2017-07-31 00:00:00' AND created_at <= '2017-10-25 22:23:42.184226') GROUP BY (DATE_TRUNC('week', (created_at::timestamptz - INTERVAL '0 day' - INTERVAL '0 second') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 day' + INTERVAL '0 second') AT TIME ZONE 'Etc/UTC'

    SELECT COUNT(*) AS count_all, (DATE_TRUNC('week', (created_at::timestamptz - INTERVAL '0 day' - INTERVAL '0 second') AT TIME ZONE 'America/New_York') + INTERVAL '0 day' + INTERVAL '0 second') AT TIME ZONE 'America/New_York' AS date_trunc_week_created_at_timestamptz_interval_0_day_interval_ FROM "events" WHERE ("events"."user_id" NOT IN (1, 3, 290, 339)) AND (created_at >= '2017-07-31 04:00:00' AND created_at <= '2017-10-25 22:24:57.912750') GROUP BY (DATE_TRUNC('week', (created_at::timestamptz - INTERVAL '0 day' - INTERVAL '0 second') AT TIME ZONE 'America/New_York') + INTERVAL '0 day' + INTERVAL '0 second') AT TIME ZONE 'America/New_York'
