### ISSUE TITLE
Does this work in relationships?

### ISSUE THREAD

**Issue by bo-oz** [ankane/groupdate#187]
I created the following scope on my Reporting model

```
  scope :amount_per_month, -> (months) {
    group_by_month(:date, last: months, reverse: true).count
  }
```

When I do:

`Report.amount_per_month(4)`

It works fine, but when I do:

`Account.reports.amount_per_month(4)`

I get a PSQL error:

`PG::GroupingError: ERROR:  column "reports.date" must appear in the GROUP BY clause or be used in an aggregate function`

Is there something I'm doing wrong?

**Comment by ankane** [comment]
@bo-oz My guess is your specific relationship is adding an extra scope. What SQL is it running?

**Comment by bo-oz** [comment]
You are right, my bad. There was a call to order in the definition of the relationship. That was causing the issue.
