### ISSUE TITLE
Summing multiple columns at once

### ISSUE THREAD

**Issue by samstickland** [ankane/groupdate#193]
Hi,

This trick to sum multiple columns works, but as you can see it doesn't return the date:

```
TimesheetEntry.group_by_week(:date, week_start: :mon).pluck("SUM(total_charge_cents)", "SUM(total_charge_client_cents)")
=> [[0.3854875e7, 0.418247e7],
 [0.4794375e7, 0.5244962e7],
...
]
```

Is there a way to do this? A field name that can be passed `pluck`?

**Comment by ankane** [comment]
Unfortunately, this is just how pluck works (consistent with ActiveRecord group).

**Comment by shawniut** [comment]
Hi! any workaround to this issue? I also need to display sum of multiple columns in a time series as shown below.

Month    SUM(GrossSale)   SUM(Discounts)     SUM(NetSale)
-----------------------------------------------------------------
Jan 2017        1200                                 200                  1000

**Comment by ankane** [comment]
No, ActiveRecord hasn't changed how `pluck` works in the past 7 days :)

**Comment by jfanals** [comment]
Hi @shawniut, a work around would be using this gem instead of pluck:
https://github.com/ankane/calculate-all
