### ISSUE TITLE
Not compatible with oracle-enhanced adapter?

### ISSUE THREAD

**Issue by parker2038** [ankane/groupdate#198]
I was planning to use this gem for a project where I need to group logs by minute but the client has an oracle DB and I get an error "Connection adapter not supported: OracleEnhanced".

the trace is:
groupdate (2.5.3) lib/groupdate/magic.rb:85:in `relation'
groupdate (2.5.3) lib/groupdate/scopes.rb:10:in `block in group_by_minute'
groupdate (2.5.3) lib/groupdate/enumerable.rb:7:in `block in group_by_minute'

is this gem not compatible with oracle? If not, are you planning to add oracle support soon?
Thanks

**Comment by ankane** [comment]
Hey @parker2038, Groupdate doesn't have Oracle support. Since it's not a very common need, there are no plans to add it.
