### ISSUE TITLE
Group_By_Day_Of_Week is off by 1 (Monday returns as Sunday)

### ISSUE THREAD

**Issue by JSanderbeck** [ankane/groupdate#202]
From a previous issue that was closed without resolution...

I have a chart that shows the number of incidents by the day of the week. The school is only open Monday thru Friday, and I verified all records are in the range of Monday thru Friday, however this line of code draws a chart from Sunday to Thursday.

@records.group_by_day_of_week(:entry_date, week_start: :sun, format: '%a').count

From the description in the previously reported bug, you stated that DAYOFWEEK returns a 1 for Sunday to a 7 for Saturday. This is incorrect in the later releases of Postgresql.

-----  From Postgresql Documentation
The function receives the date variable d as its only argument and returns an integer that indicates the day of the week for this date.

0 - Sunday
1 - Monday
2 - Tuesday
3 - Wednesday
4 - Thursday
5 - Friday
6 - Saturday

![image](https://user-images.githubusercontent.com/4447811/42606121-aaf550ba-8549-11e8-9dbb-55bf0a9e5674.png)

Any suggestions on a way around this, or is a fix coming?

John

**Comment by ankane** [comment]
Hey @JSanderbeck, check out the section on date columns in the readme to see if that fixes it.

**Comment by JSanderbeck** [comment]
I tried changing the week start and it just changed what the first day in that chart was. Sunday still contained data...

**Comment by ankane** [comment]
Try this: https://github.com/ankane/groupdate#date-columns

**Comment by JSanderbeck** [comment]
But I NEED group_by_day_of_week, not just week...

**Comment by ankane** [comment]
The specific function isn't important in the example - it's the `time_zone: false` part.

**Comment by ankane** [comment]
Anyways, I don't think this is an issue with Groupdate, but happy to revisit if there's more evidence.

**Comment by JSanderbeck** [comment]
Ok. I understand what you are saying...   That worked...
