### ISSUE TITLE
group_by_day last, default_value options argument error

### ISSUE THREAD

**Issue by ajaxprof** [ankane/groupdate#203]
Hello! Today I updates groupdate gem to 4.0.1 version and it led me to

ArgumentError (unknown keywords: last, default_value)

I used group_by_day method on Array
Was it deprecated? Didn't manage to find any info about it's deprecation.
Solved by downgrading to 3.2
Thank you for your work!

**Comment by ankane** [comment]
Hey @ajaxprof, those options only work with the ActiveRecord methods. They were silently ignored before, so you should be able to just remove them.
