### ISSUE TITLE
Create support for Firebird database

### ISSUE THREAD

**Issue by joseh-henrique** [ankane/groupdate#204]
Please give support for Firebird database.  
Support for Firebird exists
gem 'activerecord-fb-adapter' - ActiveRecord Firebird Adapter and 
gem 'fb' - Ruby Firebird Extension Library

**Comment by ankane** [comment]
Hey @joseh-henrique, thanks for the suggestion 👍  Support for new databases can add significant maintenance cost, and unfortunately, I don't think Firebird is popular enough. You could probably monkeypatch `Groupdate::RelationBuilder#group_clause` in your own app to do this.
