### ISSUE TITLE
Groupdate::Error (Be sure to install time zone support)

### ISSUE THREAD

**Issue by jordan-realfoto** [ankane/groupdate#207]
Hello,

The gem is throwing the above exception even though Time Zone Support is installed.
If I manually run the query generated I get the expected result.

I've narrowed it down to this method:

      def perform(relation, result)
        multiple_groups = relation.group_values.size > 1

        check_time_zone_support(result, multiple_groups)
        result = cast_result(result, multiple_groups)

        series_builder.generate(
          result,
          default_value: options.key?(:default_value) ? options[:default_value] : 0,
          multiple_groups: multiple_groups,
          group_index: group_index
        )
      end

In my case the result variable is a hash with null for a key (should be count_id?) and the count as the correct value (14) and thus ends up failing the check_time_zone_support test. It appears that the key isn't being set properly.

I should note I don't have a group_by clause in the query save for the `group_by_week`. If it's any help commenting out the `check_time_zone_support` and `cast_result` methods and manually setting `multiple_groups` to false seems to fix the issue.

Please let me know if you require any more information.

Group date v4.0.1
Active Record v4.2.0

**Comment by ankane** [comment]
Hey @jordan-realfoto, that error is a sanity check by Groupdate, as the SQL should never return a `nil` key unless there's an issue with time zone support. I'd try reinstalling time zone support and possibly restarting your database.

**Comment by ankane** [comment]
Cleaning up stale issues
