### ISSUE TITLE
[Idea] Make the grouping clause available to custom selects

### ISSUE THREAD

**Issue by djshitcoin** [ankane/groupdate#208]
Hello,

in my query I would like to use multiple aggregate functions at once so I am embedding them in to my query like this.

```
group_by_day(:created_at).select('sum(amount), max(rate), min(rate), avg(rate)')
```

However, it's not possible to know which row in the result corresponds to what day because the day is not included in the `select` query. Wouldn't it make sense to provide a way to include the `group by` clause in the query, for example like

```
group_by_day(:created_at).select('sum(amount), max(rate), min(rate), avg(rate), :group_clause: as day')
```

and have groupdate automatically replace :group_clause: with the generated group by clause?

**Comment by djshitcoin** [comment]
Basically something like this 
```
module Groupdate
  class RelationBuilder
    def generate
      if @relation.select_values.present?
        @relation.group(group_clause).where(*where_clause).select(group_clause + ' as period')
      else
        @relation.group(group_clause).where(*where_clause)
      end
    end
  end
end

```

which would just add the group clause itself in the select statement.

**Comment by ankane** [comment]
Hey, thanks for the suggestion. I think support for multiple aggregations is useful outside of Groupdate as well, so it makes sense for another gem to handle it. Here's one that used to work with Groupdate (not sure if it's been updated for Groupdate 4): https://github.com/codesnik/calculate-all

See #53 for a similar discussion.

**Comment by ankane** [comment]
I created a PR for Groupdate 4 support: https://github.com/codesnik/calculate-all/pull/7

It works without it, but returns times instead of dates.

**Comment by djshitcoin** [comment]
💯
