### ISSUE TITLE
Missing Some Records

### ISSUE THREAD

**Issue by Hamdan85** [ankane/groupdate#209]
hi, @ankane , thanks for your amazing work.

I think i MIGHT have found a bug, but I cant understand it quite well..

Im using 4.0.2 and when I group a collection and sum it, the last sum remains wrong (0 i think)

For example:
```ruby
r = RealEstate.where.not(published_at: nil); r.count
D, [2018-11-03T00:11:49.104738 #29] DEBUG -- :    (4.9ms)  SELECT COUNT(*) FROM "real_estates" WHERE ("real_estates"."published_at" IS NOT NULL)
=> 717
```

Then I group it:

```ruby
r.group_by_month('real_estates.published_at', range: Date.parse('01/01/2014')..(Time.now+1.month)).count.map{|k,v| v}.sum
D, [2018-11-03T00:08:11.100646 #29] DEBUG -- :    (4.9ms)  SELECT COUNT(*) AS count_all, (DATE_TRUNC('month', (real_estates.published_at::timestamptz) AT TIME ZONE 'America/Sao_Paulo')) AT TIME ZONE 'America/Sao_Paulo' AS date_trunc_month_real_estates_published_at_timestamptz_at_time_ FROM "real_estates" WHERE ("real_estates"."published_at" IS NOT NULL) AND (real_estates.published_at >= '2014-01-01 02:00:00' AND real_estates.published_at <= '2018-12-04 02:08:11') GROUP BY (DATE_TRUNC('month', (real_estates.published_at::timestamptz) AT TIME ZONE 'America/Sao_Paulo')) AT TIME ZONE 'America/Sao_Paulo'
=> 711
```
It happens the same way without the range attribute.

do you have any idea of what's wrong or maybe Im missing something?

rails 5.1.2
ruby 2.4.1

**Comment by Hamdan85** [comment]
hm, how to you like a minimal example?
I tought i was givin it correctly up there lol...

I really want to solve this, so if you want to meet me in skype, Im available lol.

Basically, i think im having issues with summer time since Im using (as you can see by the code) a brazilian timezone and we are having summer time here...

**Comment by Hamdan85** [comment]
Have you tried 'America/Sao_Paulo' ???

I cannot get anything starting november 1th,
eg: 
```ruby
RealEstate.where('published_at >= ?', Date.parse('01/11/2018')).group_by_week('published_at').count
D, [2018-11-03T03:28:05.362301 #29] DEBUG -- :    (7.7ms)  SELECT COUNT(*) AS count_all, (DATE_TRUNC('week', (published_at::timestamptz - INTERVAL '6 day') AT TIME ZONE 'America/Sao_Paulo') + INTERVAL '6 day') AT TIME ZONE 'America/Sao_Paulo' AS date_trunc_week_published_at_timestamptz_interval_6_day_at_time FROM "real_estates" WHERE (published_at >= '2018-11-01') AND (published_at IS NOT NULL) GROUP BY (DATE_TRUNC('week', (published_at::timestamptz - INTERVAL '6 day') AT TIME ZONE 'America/Sao_Paulo') + INTERVAL '6 day') AT TIME ZONE 'America/Sao_Paulo'
=> {Sun, 21 Oct 2018=>0}
```

**Comment by Hamdan85** [comment]
Surely is. Using with time_zone: false solves the issue. The problem is
that the reading becomes essentially wrong.

Em sáb, 3 de nov de 2018 22:27, Felipe Bergamo <notifications@github.com>
escreveu:

**Comment by Hamdan85** [comment]
Sure @ankane 👍 
first one: 
```ruby
=> [#<RealEstate id: nil, published_at: "2018-11-01 03:10:28">, #<RealEstate id: nil, published_at: "2018-11-01 03:12:45">, #<RealEstate id: nil, published_at: "2018-11-01 03:30:25">, #<RealEstate id: nil, published_at: "2018-11-01 03:21:10">, #<RealEstate id: nil, published_at: "2018-11-01 03:05:02">, #<RealEstate id: nil, published_at: "2018-11-01 03:37:19">]
```

Second one: 
```ruby
=> [#<RealEstate id: nil>]
```

**Comment by ankane** [comment]
I think the time zone information on your database server may be out of date. That should return `"2018-10-28 03:00:00+00"`. Before the recent time zone change (pushing back to the first week of November), that would be correct.

**Comment by Hamdan85** [comment]
Ankane, if I was the responsible for that, I would agree, but my db is a postgres mantained by heroku. I dont even log in there lol.... 

also, my DB works in UTC and I just apply timezone in the application level. So... I don't know the pratical doing here... 

Thanks

**Comment by ankane** [comment]
I just checked one of my apps on Heroku and it has the same issue. The time zone info is outdated. If you don't believe me, try:

```sh
heroku pg:psql
```

And

```sql
SET TIME ZONE  'America/Sao_Paulo';
SELECT NOW();
SELECT NOW() - INTERVAL '1 day';
```

The DST offset is the same for both days. That shouldn't be the case on the day of and before DST.

**Comment by Hamdan85** [comment]
Nice.... but now, what to do ? lol
I dont usually mess with my db lol

**Comment by ankane** [comment]
Email Heroku about it.

**Comment by ankane** [comment]
The Groupdate SQL query uses it.

**Comment by ankane** [comment]
Just released 4.1.0 which checks for this issue and alerts the user.

**Comment by Hamdan85** [comment]
I have spoken with heroku and now I know what I need to do.
But here's a question about your gem architecture: shouldnt it follow rails way and operate over UTC using the timezone in application level? I think it might be a little confunsing to use the reading from the database since most rails programmers dont even mess with db directly... is that the point isnt it?

**Comment by ankane** [comment]
Can you post the solution here so @fbbergamo and others know how to address it?

It's wayyyyy more efficient to do grouping within the database, which is why Groupdate takes this approach.

**Comment by ankane** [comment]
Thanks. I'm not sure what you're proposing, but if you find a better way to do it, feel free to submit a PR.

**Comment by Hamdan85** [comment]
Man, I just found out that you are pratically a partner in my projects... lol... 
wanna be my friend? lol all my projetcts have at least one gem of yours lol
just opened a issue in ahoy_mail... 😁

**Comment by lmontezzo** [comment]
Hey, I'm facing the same problem here, also from Brazil...
Did you guys found out a solution without using time_zone: false and leaving the app with messed up time records?

**Comment by Hamdan85** [comment]
Yes... But as I said in the last comment, you should update your dB
timezone config

Em qua, 7 de nov de 2018 17:21, Luciano Montezzo <notifications@github.com>
escreveu:

**Comment by fwuensche** [comment]
Just had the same issue and fixed it by following [Heroku instructions](https://devcenter.heroku.com/articles/updating-heroku-postgres-databases#updating-with-follower-changeover) suggested by @Hamdan85.

To illustrate, it is november and my graphs were showing data only up until october.
![image](https://user-images.githubusercontent.com/1740848/48986473-b484a800-f115-11e8-989b-a9a61d22307b.png)

In four simple steps, you can:

---

#### 1. Create a follower database
To create a follower database you can use the heroku web interface. Just go to your app and, inside Resources tab, click on your database. Go to the "Durability" tab, scroll all the way down to the "followers" session and click "Create Follower". Select the most appropriate plan and you're done.

#### 2. Set maintenance mode to on
Back to your app, go to Settings, scroll down, and set maintenance mode to on.

#### 3. Promote your new database
This is the first step I had to use the terminal. So I ran `heroku pg:info --app touts-production` to check the name of the newly created database. Then finally promoted it with `heroku pg:promote HEROKU_POSTGRESQL_ROSE_URL --app touts-production`.

#### 4. Turn off maintenance mode 
You can now set your app back to normal with `heroku maintenance:off --app touts-production`.

---

And now I can finally see the current month:
![image](https://user-images.githubusercontent.com/1740848/48986798-7f7a5480-f119-11e8-9cc7-cca3ccfa3ad0.png)

Thanks, @ankane, btw, for the awesome contributions to the community!

**Comment by Hamdan85** [comment]
in addition: it also can be done through heroku's UI
