### ISSUE TITLE
Grouping fails with ArgumentError for empty datasets and current: false

### ISSUE THREAD

**Issue by chickenburgers** [ankane/groupdate#213]
If the dataset contains no rows, and you try to group it, an exception is raised:

blank = User.where(id: "doesn't exist")
blank.group_by_week(:created_at, current: true).count => {}
blank.group_by_week(:created_at, current: false).count => ArgumentError

It should return an empty Hash.

The bug is [here](https://github.com/ankane/groupdate/blob/ff4c92e0005e60cc98e9e1ee418ecde4edc50bbc/lib/groupdate/series_builder.rb#L161)

`if options[:current] == false && round_time(now) >= tr.last`

`tr.last` is nil, and then the comparison of a TimeWithZone with nil fails

**Comment by ankane** [comment]
Hey @chickenburgers, thanks for reporting 👍 Fixed on master.
