### ISSUE TITLE
Download Top 10 List

### ISSUE THREAD

**Issue by emrahyildirim** [ankane/groupdate#214]
Hi,

I've done a lot with this ship. I congratulate you. A very handy gem

I find the maximum number of downloads with the code I use below. however, I want to add who did it.

username download created_at
john 13.9 MB 2019-02-02 08:56:55 UTC
terry 52.3 MB 2019-02-02 09: 42: 44UTC
maria 145.5 MB 2019-02-02 10:34:12 UTC
lynda 65.2 MB 2019-02-02 10: 50: 52UTC
mark 254 MB 2019-02-02 14:52:12 UTC

<% = @items.group_by_day (: created_at, last: 1) .maximum (: downloads) .map {| k, v | number_to_human_size (v)} join (",")%>

I also want to bring the 5 users who downloaded the most.

Can you help me?

Thanks!

**Comment by ankane** [comment]
Hey @emrahyildirim, check out the Contributing Guide for where to get help with your code.
