### ISSUE TITLE
`last` option ends at current time instead of current period

### ISSUE THREAD

**Issue by kapso** [ankane/groupdate#217]
I am running the following query, which looks fairly standard...

`store.orders.group_by_day(:order_at, last: 1).count`

...and I am seeing the following data range in the query - `("orders"."order_at" >= '2019-04-02 00:00:00' AND "orders"."order_at" <= '2019-04-02 01:52:42.823299')`

...but I feel the end part of date range may not be correct? Shouldn't that be `2019-04-02 23:59:59` instead of `2019-04-02 01:52:42.823299` ??

Using the following versions:

Rails: `5.2.3`
Ruby: `2.6.2`
groupdate: `4.1.1`

This is on my local macOS, with PST as the timezone.

**Comment by ankane** [comment]
Hey @kapso, it was designed to end at the current time, but I can see how ending at the end of the current period would be more intuitive. It'd be safest to wait until Groupdate 5 to make this change.

**Comment by kapso** [comment]
@ankane thanks for the response, and your work on this gem. Do you know how far is version 5?

**Comment by ankane** [comment]
My best guess would be a year or so.

**Comment by kapso** [comment]
@ankane Thats further away. I was thinking maybe this change can be config driven - meaning default will be the current behavior unless someone does this...

```ruby
Groupdate.configure do |config|
  config.end_range = :current_period # or :current_time
end

**Comment by ankane** [comment]
I don't think it's worth the effort to add an option. You can always fork if you need it now. I've added it to #218.

**Comment by kapso** [comment]
@ankane Got it, I understand. I will probably fork it. 

It will be helpful if you can point me to the part which is grabbing the current time? Thanks a lot.

**Comment by ankane** [comment]
https://github.com/ankane/groupdate/blob/f9c824a9b7df479f64facd293e50bd47efb7c499/lib/groupdate/series_builder.rb#L120
