### ISSUE TITLE
range for hash values do not show all days of week

### ISSUE THREAD

**Issue by muhammadn** [ankane/groupdate#221]
range option for `.group_by_day_of_week` does not show all the days that were missing with data from an array of hashes. 

The current output output only shows tuesday and wednesday.
```
> Hash[ hashes.group_by_day_of_week(range: 1.week.ago...Time.now) { |u| u.created_at }.map { |k, v| [k, v.size] } ]
 => {2=>17, 3=>11}
```

expected output:
{0=>0, 1=>0, 2=>17, 3=>11, 4=>0, 5=>0, 6=>0}

which would be correct if i were to use non array/hash values (eg. from ActiveRecord) using
`ardata.group_by_day_of_week(:created_at, range: 1.week.ago...Time.now).count`

**Comment by muhammadn** [comment]
Managed to do a workaround:

```
         hashes = current_user.url_hashes.includes(:url_hash_counts).map {|url| url.url_hash_counts }.flatten
         hashes = hashes.group_by_day_of_week(range: 1.week.ago..Time.now) { |t| t.created_at }.map { |k, v| [k, v.size] }
         # set missing days to value 0
         (0..6).each { |n|
           days = hashes.select{|x, y| x == n}
           if days.empty?
             arr = [n, 0]
             hashes.push(arr)
           end
         }
         # sort by day
         hashes.sort {|a,b| a[0] <=> b[0]}
```

**Comment by ankane** [comment]
Hey @muhammadn, you can use `series: true` for this.

**Comment by muhammadn** [comment]
@ankane Thank you so much for the gem!
