### ISSUE TITLE
Another take on 'Database and Ruby have inconsistent time zone info'

### ISSUE THREAD

**Issue by feliperaul** [ankane/groupdate#222]
Ankane, I have carefully read through #215 and #209, but I still think I'm onto something different here and, regardless, those two issues couldn't help us reaching a solution.

We have a `User` has 3 reservations in the month of november/2019:

```
this is in production: 
user.reservations.where("DATE(check_in) >= :start_date AND DATE(check_in) <= :end_date", start_date: Date.parse("2019-11-01"), end_date: Date.parse("2019-11-30")).pluck(:check_in)

=> [Thu, 07 Nov 2019 12:00:00 -03 -03:00,
 Wed, 13 Nov 2019 12:00:00 -03 -03:00,
 Thu, 21 Nov 2019 16:00:00 -03 -03:00]
```

In development (after importing the production DB dump), if we group them by day, we get exactly what we expect: 

```
user.reservations.where("DATE(check_in) >= :start_date AND DATE(check_in) <= :end_date", start_date: Date.parse("2019-11-01"), end_date: Date.parse("2019-11-30")).group_by_day(:check_in, series: false).count

=> {Thu, 07 Nov 2019=>1, Wed, 13 Nov 2019=>1, Thu, 21 Nov 2019=>1}
```

In production, we get an empty hash:

```
user.reservations.where("DATE(check_in) >= :start_date AND DATE(check_in) <= :end_date", start_date: Date.parse("2019-11-01"), end_date: Date.parse("2019-11-30")).group_by_day(:check_in, series: false).count

=> {}
```

First of all, this only happens in the month of november/2019. If we try to do the same in september, october, it works perfectly and the results of production and development are the same.

Suspecting of a gem bug, we upgraded from 4.0.1 to 4.1.2, and now we started having the exception:

```
user.reservations.where("DATE(check_in) >= :start_date AND DATE(check_in) <= :end_date", start_date: Date.parse("2019-11-01"), end_date: Date.parse("2019-11-30")).group_by_day(:check_in, series: false).count

=> Groupdate::Error: Database and Ruby have inconsistent time zone info. Database returned 2019-11-06 23:00:00 -0300
```

Passing `time_zone: false` as an argument makes production return correct results. 

What doesn't make sense is why would the discrepancy not happen in the month of Sep, but only in October. 

Also, the error message returned, `Database returned 2019-11-06 23:00:00 -0300`, doesn't help us much because the first record returned has a check_in of `Thu, 07 Nov 2019 12:00:00 -03 -03:00`, so midday of november 7th, very far from midnight that could be causing any troubles when going from UTC to -3. 

We could just throw the `time_zone: false` arg, because it appears to not be messing up with our results, but we're afraid of future implications and would have to rewrite quite some code.

What is you general recommendation about this? Changing the production database timezone from UTC would go against Rails conventions and is strongly discouraged from all hosted databases services (like AWS RDS). Is that really what we should do to solve this?

PS:
Both production and development are running the same version of MySql 5.7. 

In production, the DB is in UTC:

```
mysql> SHOW VARIABLES LIKE '%time_zone%';
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | UTC    |
```

In development, the DB is in Brazil timezone, which I can only assume mysql took automatically when it was installed since I never changed it myself:

```
mysql> SHOW VARIABLES LIKE '%time_zone%';
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | -03    |
```

**Comment by odlp** [comment]
Signposting for others who might be experiencing 'Database and Ruby have inconsistent time zone info': There is an issue affecting the `tzinfo` gem - it's incompatible with timezone-data 2020b (onwards?). Recent versions of [Alpine ship with 2020c](https://pkgs.alpinelinux.org/package/v3.12/main/x86_64/tzdata) for example. The file format changed from 'fat' to 'slim' which isn't compatible with the `tzinfo` gem yet.

Resources:

- [Issue on tzinfo gem](https://github.com/tzinfo/tzinfo/issues/120)
- [Workarounds in Ruby and Alpine/Docker](https://stackoverflow.com/a/64594297/703903)

**Comment by inyerade** [comment]
Thanks @odlp I solved my problem with:

    bundle update tzinfo

**Comment by nuzelac** [comment]
In case anyone encounters similar issue, I was running my app inside Docker container with outdated `tzdata` and a PostgreSQL on the host machine with latest tzdata. Solution was to update tzdata inside Dockerfile.

**Comment by snex** [comment]
I am experiencing this issue even after updating everything I can regarding timezones. Strangely, I only receive the error when using "includes" on my model.

Model.group_by_month(:date).sum(:result)
=> works as expected

Model.includes(:some, :other, :model).group_by_month(:date).sum(:result)
=> Groupdate::Error (Database and Ruby have inconsistent time zone info. Database returned 2019-04-01 07:00:00 UTC)

These other models are pure lookup tables and don't even have any date columns on them.

**Comment by cgeoffray** [comment]
Same issue when using includes on my model.
=> I solved it by using joins

Model.includes(:some, :other, :model).group_by_month(:date).sum(:result)
replaced by:
Model.joins(:some, :other, :model).group_by_month(:date).sum(:result)

**Comment by simonfranzen** [comment]
We can reproduce this bug as well like @snex wrote in the post before. Only if we use a `.includes()` the error occurs. We had a combination of includes and left_outer_joins.

Our timezone in rails config is set to "Europe/Berlin"
Our psql database uses the ETC/UTC without offset.

**Comment by ankane** [comment]
If someone wants to submit a PR with a failing test case for the `includes` issue, I can look into it further.

**Comment by aried3r** [comment]
It's not a PR, but while researching another issue that only began occurring after updating to Rails 6.1 I've written a test case that shows the issue, I believe.

For this to work, you have to first:

```Console
$ createdb groupdate-rails61
```

Then run:

```Ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Works with rails 6.0.0.
  gem "rails", "~> 6.1.0"
  gem "pg"
  gem "groupdate"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "groupdate-rails61")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class TestApp < Rails::Application
  # If you comment this out, the test case works as expected.
  config.time_zone = "Europe/Berlin"
end

Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table :comments, force: true do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    Post.create!(created_at: 11.months.ago)

    # Works
    pp Post.group_by_month(:created_at, last: 12, format: '%B').count

    # Also works
    pp Post.left_outer_joins(:comments).where(comments: { id: nil }).group_by_month(:created_at, last: 12, format: '%B').count

    # Only works if the time zone is not configured.
    pp Post.includes(:comments).where(comments: { id: nil }).group_by_month(:created_at, last: 12, format: '%B').count
  end
end
```

The test case doesn't assert anything right now, but just raises an exception. You can move the code outside the test case if you like.

If you comment out the `config.time_zone` line, it Works on My Machine™.

Leaving this line in there, it works with Rails 6.0 (change the version constraint at the top of the file), but doesn't with Rails 6.1. I'm not sure if it's a Rails issue or if it's groupdate or the fact that Rails 6.1 uses `tzinfo` 2.x instead of 1.x or a combination.

My only assumption is that it's not that columns are timezone aware, I think that's for Rails 7: https://github.com/rails/rails/pull/41395.

**Comment by ankane** [comment]
Hey @aried3r, thanks for the repro script! Just pushed a fix (the issue was affecting `includes` with Rails 6.1+) if you point your Gemfile to GitHub.

Also, for Groupdate 6, I've updated the gem to work when time zones are inconsistent, so this error won't appear anymore.
