### ISSUE TITLE
Grouping by months for a particular year

### ISSUE THREAD

**Issue by eshwarg** [ankane/groupdate#223]
Hi,

Before creating an issue, please check out the Contributing Guide:

https://github.com/ankane/groupdate/blob/master/CONTRIBUTING.md

Thanks!

**Comment by eshwarg** [comment]
Can we group by months for a particular year. Right now i am having results for both the years 2018 & 2019 and i want to filter by month for the year 2019 only

**Comment by ankane** [comment]
Hey @eshwarg, check out the Contributing Guide for where to get help.
