### ISSUE TITLE
Problems of Timezone Brazil. Thanks

### ISSUE THREAD

**Issue by andersonxrilo** [ankane/groupdate#224]
Hi,

In Brazil, this year summer time has been abolished. Exactly at that time all clocks would go into spindle change. So the gem is giving error in function "check_consistent_time_zone_info". It keeps returning that the date time is inconsistent, and returns a date one hour earlier, which would be the time if we were in daylight saving time, but that's not the case.
That is, the gem has stopped working in my project.

To be clear, in Brazil, daylight saving time was a UTC change from -3: 00 to -4: 00. This has been removed, but the gem still considers it somehow.

Thank you for your willingness and your work.

Before creating an issue, please check out the Contributing Guide:

https://github.com/ankane/groupdate/blob/master/CONTRIBUTING.md

Thanks!

**Comment by ankane** [comment]
Hey @andersonxrilo, check out #215 and #222. This is an issue with your environment rather than Groupdate.

**Comment by andersonxrilo** [comment]
Thanks, my RDS Postgres Version has upgraded, was in version 10.6 and went to 10.10. Thanks for the quick response.

**Comment by ankane** [comment]
Awesome, glad that fixed it!
