### ISSUE TITLE
Database missing time zone support for Etc/UTC

### ISSUE THREAD

**Issue by quangvv-1620** [ankane/groupdate#226]
I can't using group_by_day because database missing time zone support for utc.
I also doing sush as you recommented [here](https://github.com/ankane/groupdate#for-mysql). But it not working in my app.
Thanks

**Comment by ankane** [comment]
Hey @quangvv-1620, unfortunately, there's not much I can do to help to get time zone support installed. Make sure there are no errors when you run the time zone SQL statements. If you use a hosted MySQL provider, you can try asking their support team as well.
