### ISSUE TITLE
Fiscal / User-defined calendars

### ISSUE THREAD

**Issue by frizman21** [ankane/groupdate#228]
Have you considered support for user defined calendars? For example, a fiscal calendar that has number of weeks per month using a [4-4-5](https://en.wikipedia.org/wiki/4%E2%80%934%E2%80%935_calendar) pattern for a quarter?

**Comment by ankane** [comment]
Hey @frizman21, that's an interesting idea, but I think it's outside the scope of what I'd want to support right now.

For the 4-4-5 example, you can use `group_by_week` and combine the results in memory for calculations like `count` and `sum`.
