### ISSUE TITLE
Add support for grouping by every N number of seconds/minutes/etc.

### ISSUE THREAD

**Issue by tybro0103** [ankane/groupdate#23]
I don't currently see any way to group by something like every 10 minutes. Should be simple to add... just do a mod N after the date_trunc.

**Comment by danieljacobarcher** [comment]
+1 Would love this too.

**Comment by jcarpanelli** [comment]
+1, this feature would be awesome!

**Comment by mustela** [comment]
+1, would be great to have this one!

**Comment by pchaganti** [comment]
+1, this would be awesome!

**Comment by alexkrolick** [comment]
I'd really like to be able to be group by a customizable amount of days. E.g.:

`Thing.group_by_days(:date_column, params[:number_of_days]).count`

**Comment by alexkrolick** [comment]
@ankane this is a really old request, any thoughts on closing it or are you still considering it?

**Comment by edwardmp** [comment]
This would be great, as right now there is no option to group by a month exactly. For instance, I have a record created at the 26th of september, and I want the group only the last 30 days. Right now, if I group by a month this record would be excluded as it group period starts at october 1st. But what I really want is all records created in the last 30 days, starting at 30 days ago and not the 1st day of the month.

**Comment by ankane** [comment]
Quick update: still happy to review a PR for this. My recommended interface would be

```ruby
group_by_duration(5.minutes, column, options)
```

**Comment by ankane** [comment]
Just added this on the `group_by_duration` branch.

```ruby
gem 'groupdate', github: 'ankane/groupdate', branch: 'group_by_duration'
```

You can use it with:

```ruby
User.group_by_duration(10.minutes, :created_at).count
```

For those still interested in this feature, please let me know your feedback.

**Comment by alexanderadam** [comment]
> For those still interested in this feature, please let me know your feedback.

IMHO this is a great thing! I just can't test in the nearer future.

**Comment by ankane** [comment]
Update: Decided to go with a new option instead of a new method to avoid the confusion mentioned above. `group_by_minute` and `group_by_second` now have an `n` option.

```ruby
User.group_by_minute(:created_at, n: 10).count # 10 minutes
```

It's currently on master with the plan to be merged next week. Please let me know if you have any feedback.
