### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [ankane/groupdate#231]
Groupdate 6

- [x] Raise error for non-attribute `column` argument without `Arel.sql`
- [x] Return dates in SQL for day, week, month, quarter, and year - `date_queries2` branch AND remove `dates` option
- [x] Raise error for ranges with string bounds (`.."2020-01-01"` currently only includes first second of day, unlike `..Date.parse("2020-01-01")` - alternatively, we could try to detect dates)
- [x] Drop support for Active Record < 5.2 and Ruby < 2.6

Ideas

- [x] Support endless ranges in `range` option - `endless_range2` branch
- [x] Support beginless ranges in `range` option

**Comment by jeffblake** [comment]
Thanks for the release! For fear of asking too much, do you mind merging master into `group_by_duration`?

**Comment by ankane** [comment]
np, merged

**Comment by nhh** [comment]
Is `group_by_duration` available on master? If so, are there any docs? Thanks!!

**Comment by ankane** [comment]
Hey @nhh, see https://github.com/ankane/groupdate/issues/23#issuecomment-663263540 for the latest update.

**Comment by nhh** [comment]
@ankane thank you!

Whats the reason behind dropping "group_by_duration" in favor of steps "n".?

I really liked the group_by_duration method, because it feels "intuitive" and the ruby way. But reasons are probably technical, right?

**Comment by ankane** [comment]
@nhh I think it'll be less confusing for users. See https://github.com/ankane/groupdate/issues/23#issuecomment-563899152.

**Comment by gekong** [comment]
I'm building a multi model chart by doing
model1.where('created_at < ?', Time.now).where('created_at > ?', Time.now - 14.days).group_by_day(:created_at).count
model2.where('created_at < ?', Time.now).where('created_at > ?', Time.now - 14.days).group_by_day(:created_at).count
the list created only lists each day that has a record and not the days that don't 
is there a way to force this to show the count 0 on days that don't have any records? (this only happens in beginnings and endings)
I hope I have explanation makes sense.

**Comment by gekong** [comment]
![image](https://user-images.githubusercontent.com/19486/112641613-e65ac600-8e18-11eb-95f0-04694fa7f05d.png)

**Comment by ankane** [comment]
Hey @gekong, if you use the [range option](https://github.com/ankane/groupdate#time-range) instead of `where` to limit the time range, it'll fill in zeros at the start and end.

**Comment by gekong** [comment]
> Hey @gekong, if you use the [range option](https://github.com/ankane/groupdate#time-range) instead of `where` to limit the time range, it'll fill in zeros at the start and end.

Awesome my bad!
