### ISSUE TITLE
[Idea] An option to include `group clause` in selected result

### ISSUE THREAD

**Issue by xiuzhong** [ankane/groupdate#235]
Hi,

I used `groupdate` in an unusual way: not with ActiveRecord::Calculations, instead manually selecting the calculation like:
`sql = "COUNT(*) AS count, AVG(delivery.volume/truck.capacity) AS percentage, MIN(collected_at) AS collected_at"`

`Delivery.select(sql).group_by_day(:collected_at).to_a` 

It works well except the series label is not included in the result, so we have to use `MIN(collected_at)` to have it, then convert it to the correct label in ruby code.

I was thinking of a new option like `series_label: collected_at_date`, so it indicates the group clause should be included in the result and can be accessed by the method `collected_at_date`.
 
Obviously this option works only when `groupdate` is not used together with ActiveRecord::Calculations.

Let me know if this feature deserves a PR and I'm happy to contribute if so.

**Comment by ankane** [comment]
Hey @xiuzhong, thanks for the suggestion! Unfortunately, I'm not sure there's currently a way to control the column name. Groupdate had a hack for friendly names in the past, but it no longer works with recently versions of Rails. However, if you know of a way, happy to consider it.

The `calculate-all` gem was also a clean way to do this, but doesn't appear to be maintained. I submitted a PR for Groupdate 4+ support, but it's still awaiting review: https://github.com/codesnik/calculate-all/pull/7

**Comment by xiuzhong** [comment]
Thanks for the background. 
I had an idea, will submit a PR later.

**Comment by ankane** [comment]
Cleaning up issues. See discussion in #239.
