### ISSUE TITLE
[Idea] Support SQL Server 2016 and later by `AT TIME ZONE`

### ISSUE THREAD

**Issue by xiuzhong** [ankane/groupdate#236]
I've stretched the `groupdate` to support SQL Server, just wondering if you're interested with it?

**Comment by ankane** [comment]
Hey @xiuzhong, on the fence about officially supporting SQL server (since it's less popular in the Ruby community), but would be great to see the code. If it's fairly straightforward and easy to test (I've used Docker to test SQL server in the past), we can probably add it.

**Comment by xiuzhong** [comment]
@ankane Thanks for the comment.
Exactly SQL Server is not popular. Unfortunately, we have to support MySql and SQL server with the same code base. That's why I like to stretch **groupdate**  gem.

I will submit a PR later for your review.

Regarding the test, SQLserver 2018@Docker is the way I'm doing. 

Last, many thanks for the wonderful gem **groupdate**

**Comment by ankane** [comment]
Cleaning up issues. See discussion in #239.

**Comment by jonahgeorge** [comment]
@ankane A few years later, would you be willing to consider a more conservative patch adding SQL Server support (without timezones)?

**Comment by imtiazwazir** [comment]
+1
