### ISSUE TITLE
Accumulate instead of counting for period

### ISSUE THREAD

**Issue by jvillarejo** [ankane/groupdate#237]
Hi,

This is a question more than an issue. 
I'm trying to do an accumulation of the count.

For example If I want to count sign ups since period:

```ruby
range = Time.new(2019,12,1)..Time.zone.now
SignUp.group_by_week(:created_at, range: range)

{Sun, 01 Dec 2019=>4,
 Sun, 08 Dec 2019=>7,
 Sun, 15 Dec 2019=>7,
 Sun, 22 Dec 2019=>7,
 Sun, 29 Dec 2019=>7,
 Sun, 05 Jan 2020=>8,
 Sun, 12 Jan 2020=>8,
 Sun, 19 Jan 2020=>9,
 Sun, 26 Jan 2020=>9,
 Sun, 02 Feb 2020=>11,
 Sun, 09 Feb 2020=>13,
 Sun, 16 Feb 2020=>16,
 Sun, 23 Feb 2020=>18,
 Sun, 01 Mar 2020=>27,
 Sun, 08 Mar 2020=>32,
 Sun, 15 Mar 2020=>32,
 Sun, 22 Mar 2020=>32}
```
Is there a way to do that directly with `groupdate`? I also expect that it starts with the total count previous the period I pass as argument. 
I this case `4` was the total number before `2019-12-01`

Thanks!

**Comment by ankane** [comment]
Hey @jvillarejo, Groupdate doesn't provide any calculation methods like cumulative count/sum, but you should be able to create a helper in your application to do the accumulation.

**Comment by jvillarejo** [comment]
Thanks for your reply @ankane 
Yes I've done that. But I thought it would be good to directly calculate all with the DB. 
Would you consider a good feature to implement? I can try to make a PR for it with your guidance and approval

**Comment by ankane** [comment]
I think this would be better as a separate gem.

**Comment by duleorlovic** [comment]
Solution is so simple that there is no need to create a gem https://github.com/ankane/groupdate/issues/75#issuecomment-1254957045

**Comment by danielricecodes** [comment]
> Solution is so simple that there is no need to create a gem [#75 (comment)](https://github.com/ankane/groupdate/issues/75#issuecomment-1254957045)

Agreed.  A PR adding an `accumulate: true` option to any of the `group_by` methods would be a fantastic addition to this gem.  This is not an uncommon use case!
