### ISSUE TITLE
Group by duration that is more than 2.hours

### ISSUE THREAD

**Issue by evgeniy-khlopin** [ankane/groupdate#238]
Hi. Thanks for this nice gem.
I'm not sure if this an issue. It's rather a question

There is a query:
`User.group_by_duration(30.days, :created_at, range: 3.month.ago..Date.today).count`

Expected result: `{Tue, 10 Dec 2019 00:00:00 UTC +00:00=>2, Thu, 09 Jan 2020 00:00:00 UTC +00:00=>5, Sat, 08 Feb 2020 00:00:00 UTC +00:00=>3, Mon, 09 Mar 2020 00:00:00 UTC +00:00=>1}`

Actual result: `{Tue, 10 Dec 2019 00:00:00 UTC +00:00=>0, Thu, 09 Jan 2020 00:00:00 UTC +00:00=>0, Sat, 08 Feb 2020 00:00:00 UTC +00:00=>0, Mon, 09 Mar 2020 00:00:00 UTC +00:00=>0}`

I've tried to use `group_by_month`, but this method counts the results from the beginning of the month.

So the question is if this a proper way to use `group_by_duration` to achieve the result I've described above?

Thanks!

**Comment by ankane** [comment]
Hey @evgeniy-khlopin, `group_by_duration` only works with the following durations right now: 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30 seconds/minutes.

**Comment by evgeniy-khlopin** [comment]
@ankane Thanks for your reply, I'm closing the issue
