### ISSUE TITLE
Clarification on README

### ISSUE THREAD

**Issue by blakegearin** [ankane/groupdate#243]
Hi, I'm trying to learn how to use groupdate and I'm having a hard time understanding what type of object `User` is supposed to represent in the following provided examples:

```ruby
User.group_by_day(:created_at).count
User.group_by_week(:created_at, time_zone: "Pacific Time (US & Canada)").count
```

Is there some assumption I'm missing here, such as the use of a database? Why is there a different syntax for arrays?

**Comment by ankane** [comment]
Hey @blakegearin, `User` is an Active Record model. Grouping on the database-level is different from grouping arrays in memory, which is why the syntax is different.

**Comment by blakegearin** [comment]
That makes sense, thanks for answering. I don't have Rails/Active Record in the project I'm currently working on, and the documentation didn't seem to indicate the primary use case requires it

**Comment by ankane** [comment]
The primary use case is database grouping, but Active Record isn't required if you just need it for arrays and hashes.
