### ISSUE TITLE
Conflict with gems that override ActiveRecord::Relation#calculate

### ISSUE THREAD

**Issue by RobertoSchneiders** [ankane/groupdate#244]
I have an issue with `groupdate` when combined with the latest version of `activerecord-sqlserver-adapter`. The sqlserver-adapter gem is overriding the ActiveRecord::Relation#calculate with a prepend as you can see [here](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/65331d23ec925d92113a768a0d225de9ef389d28/lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb#L51). with that, the `groupdate` calculate method is never executed, causing weird issues that are not obvious until you start debugging the gem. 

I was able to fix the issue by prepending the `groupdate` calculate method as well, so both methods are executed (you have to be aware of the load order). This is the patch I used:

```
module Groupdate
  module RelationPatch
    extend ActiveSupport::Concern

    def calculate(*args, &block)
      default_value = [:count, :sum].include?(args[0]) ? 0 : nil
      Groupdate.process_result(self, super, default_value: default_value)
    end
  end
end

ActiveRecord::Relation.prepend(Groupdate::RelationPatch)
```

can we change `groupdate` to prepend instead of including the relation concern? if we do that I would be able to fix this issue just by moving the `groupdate` gem to the end of the gemfile instead of having to patch it.

**Comment by ankane** [comment]
Hey @RobertoSchneiders, I think it'd be better for `activerecord-sqlserver-adapter` to use `super` for non-SQL server adapters.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by jonahgeorge** [comment]
This has now been fixed in `activerecord-sqlserver-adapter`: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/commit/1beb276cce652559505d2c1529071c48d8ed0bb4
