### ISSUE TITLE
TimescaleDB support

### ISSUE THREAD

**Issue by rept** [ankane/groupdate#245]
Hi,

Thanks for this wonderful gem.  Together with ChartKick I can generate charts super easy with grouping.

Are there any plans for TimescaleDB support?  This runs on default Postgres but requires queries like this:

    SELECT time_bucket('1 day', date) AS "one_day", sum(consumption) from con_details
    group by one_day

**Comment by ankane** [comment]
Hey @rept, thanks for the suggestion. I don't think it's common enough to officially support, but you should be able to fork and add it here for your project: https://github.com/ankane/groupdate/blob/196d92f039951b39872e24ece3f32eda89889d45/lib/groupdate/relation_builder.rb#L29

**Comment by rept** [comment]
Ok thx!

**Comment by ankane** [comment]
Just fyi, I added the concept of adapters on master, which should make this easier to add (however, it's an internal/non-official API, so it may break between releases).
