### ISSUE TITLE
X must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by yshmarov** [ankane/groupdate#246]
Recently groupdate stopped working for some of my models (but works OK for others!)

If I run `= Payment.all.group_by_month(:created_at).count` => Errors that I am getting:

![image](https://user-images.githubusercontent.com/13472945/104391145-91105780-553f-11eb-8180-e674e2add9c4.png)
![image](https://user-images.githubusercontent.com/13472945/104391158-98376580-553f-11eb-8f82-02a15c616899.png)

My stack:
ruby "2.7.2"
gem "rails", "~> 5.2.4.4"
groupdate (5.2.1)

**Comment by yshmarov** [comment]
Ok issue solved. If in your model you have a `default scope` set like
```
default_scope { order(created_at: :desc) }
```
than groupdate won't work for some reason

**Comment by ankane** [comment]
Hey @yshmarov, glad you figured it out. That's expected with `order` scopes (including default scopes). Groupdate follows the same behavior as Active Record's `group` method.
