### ISSUE TITLE
unexpected results with timezone and group_by_day

### ISSUE THREAD

**Issue by axlekb** [ankane/groupdate#248]
The timezone option is not giving me the results I expected.  Perhaps I am misunderstanding the use case?

My timestamps are stored in UTC in Postgres, so I expected...

`orders.group_by_day(:processed_at, time_zone: 'America/New_York').count`

...would tell me how many in each New York day based on the UTC processed_at.

However, if I look at the resulting `group_by_date` timestamp next to the original timestamp, I see that when UTC flips over to the next day, so does the `group_by_day` query.

`***` indicator added by me
```
        processed_at        | date_trunc_day_orders_processed_at_timestamptz_at_time_zone_ame 
----------------------------+-----------------------------------------------------------------
 2021-02-17 23:54:56        | 2021-02-17 00:00:00-05
 2021-02-17 23:57:53        | 2021-02-17 00:00:00-05
 2021-02-17 23:57:23        | 2021-02-17 00:00:00-05
 2021-02-18 00:01:33        | 2021-02-18 00:00:00-05  ***
 2021-02-18 00:06:53        | 2021-02-18 00:00:00-05  ***
 2021-02-18 00:11:34        | 2021-02-18 00:00:00-05  ***
```

I would have expected this:
```
        processed_at        | EXPECTED 
----------------------------+-----------------------------------------------------------------
 2021-02-17 23:54:56        | 2021-02-17 00:00:00-05
 2021-02-17 23:57:53        | 2021-02-17 00:00:00-05
 2021-02-17 23:57:23        | 2021-02-17 00:00:00-05
 2021-02-18 00:01:33        | 2021-02-17 00:00:00-05  ***
 2021-02-18 00:06:53        | 2021-02-17 00:00:00-05  ***
 2021-02-18 00:11:34        | 2021-02-17 00:00:00-05  ***
```

If I change the casting `::timestamptz` to `AT TIME ZONE 'utc'` I get the expected result.

The README section on "Time Zones" was sparse, so not sure if this is a bug, or if I'm not understanding the use case.

![image](https://user-images.githubusercontent.com/2972314/111644832-935c8f80-87d6-11eb-9c0b-4cfcbbd1ad34.png)

Thanks for your help

**Comment by ankane** [comment]
Hey @axlekb, is your database session time zone set to something other than UTC?

```ruby
ActiveRecord::Base.connection.execute("SHOW timezone").first
```

**Comment by axlekb** [comment]
It is not.

```
ActiveRecord::Base.connection.execute("SHOW timezone").first
   (4.3ms)  SHOW timezone
=> {"TimeZone"=>"UTC"}
```

**Comment by ankane** [comment]
Thanks for checking. Not really sure how to reproduce. Can you try adding a failing test to the test suite?

**Comment by axlekb** [comment]
Thanks for your help.  Dug deeper, and I'll chalk this one up to not realizing that the SQL GROUP BY date is still a "work in progress"  and more work is done outside SQL.  Apologies.  Was attempting to copy the raw queries for a materialized view.
