### ISSUE TITLE
Database missing time zone support for Etc/UTC

### ISSUE THREAD

**Issue by rahul-onekingslane** [ankane/groupdate#252]
Database missing time zone support for Etc/UTC - see https://github.com/ankane/groupdate#for-mysql

`mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql`
After executing above query, got below error

Warning: Unable to load '/usr/share/zoneinfo/+VERSION' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.

**Comment by ankane** [comment]
Hey @rahul-onekingslane, that error means time zone support isn't installed. Check out the Contributing Guide for where to get help.
