### ISSUE TITLE
Deprecation warning in Rails 7

### ISSUE THREAD

**Issue by seanwmitchell** [ankane/groupdate#253]
Hey there, your Gem has been amazing. I appreciate it.

I'm getting this deprecation warning in Rails 7.0.0alpha2:

`DEPRECATION WARNING: ActiveRecord::Base.default_timezone is deprecated and will be removed in Rails 7.1.
Use 'ActiveRecord.default_timezone' instead.`

This line had your 'group_by_day_of_week' function.

I'm sorry I'm not expert enough to make a pull request and fix it myself. Seems a quick one to fix though.

**Comment by ankane** [comment]
Hey @seanwmitchell, Rails 7 won't be officially supported until the 7.0.0 release, but you can point your Gemfile to GitHub to get rid of the warning.

```ruby
gem 'groupdate', github: 'ankane/groupdate'
```
