### ISSUE TITLE
[Idea] Group by hour of the week

### ISSUE THREAD

**Issue by fedegl** [ankane/groupdate#258]
Hi, here is an idea for a new type of grouping.

The grouping options right now include **by_hour_of_day** or **by_day_of_week** but there isn't a **by_hour_of_week**.

This grouping would be useful to create a Heatmap of a visits by hour of the week, similar to the one Google Analytics has.

<img width="335" alt="Screen Shot 2022-01-21 at 9 26 16" src="https://user-images.githubusercontent.com/17049/150572365-d49532e4-1ac8-4f64-80db-ae2a6ad1db0c.png">

Thanks for the awesome suite of libraries for Analytics!

**Comment by ankane** [comment]
Hey @fedegl, you can do:

```ruby
Visit.group_by_day_of_week(:started_at).group_by_hour_of_day(:started_at).count
```
