### ISSUE TITLE
Any future plan for supporting clickhouse adapter?

### ISSUE THREAD

**Issue by gowthamgts** [ankane/groupdate#259]
Hello, I'm using https://github.com/PNixx/clickhouse-activerecord for connecting to clickhouse database. Any plans to support 'clickhouse' adapter in future?

I understand that's not an official library to support, but pulling in data from clickhouse for charting would be a common workflow?

**Comment by ankane** [comment]
Hey @gowthamgts, I don't have any plans to support it, but you could create an adapter for it (https://github.com/ankane/groupdate/tree/master/lib/groupdate/adapters). Just note that it's an internal API, so it could break between releases.
