### ISSUE TITLE
group_by_year.group_by_month label and result issue

### ISSUE THREAD

**Issue by helmutrs** [ankane/groupdate#260]
Hi,

When creating a where(paid_on: 1.year.beginning_of_year..Date.today.end_of_year).group_by_year(:paid_on).group_by_month_year(:paid_on, format: '%b %Y').where(paid_on: 2.years.ago.beginning_of_year..Date.today.end_of_year)

it shows: 
{[Wed, 01 Jan 2020, "Dec 2014"]=>0.65571863e6,
 [Fri, 01 Jan 2021, "Dec 2014"]=>0,
 [Wed, 01 Jan 2020, "Nov 2014"]=>0.62494009e6,
 [Fri, 01 Jan 2021, "Nov 2014"]=>0,
 [Wed, 01 Jan 2020, "Oct 2014"]=>0.120136082e7,
 ....]} it mixed 2014 and 2021..2020
 
The label is not correct and results either, If I apply this to mysql gave me a different results (no zero results).

**Comment by ankane** [comment]
Hey @helmutrs, `month_of_year` only returns the month, not the year, so any formats with year (like `%Y`) will have unexpected results. Also, if you're seeing other issues, please use [this gist](https://gist.github.com/ankane/06c96968489725b789734ead0e714f4a) to reproduce.
