### ISSUE TITLE
[Idea] Average non-unique hash keys (group_by_day w/ :format)

### ISSUE THREAD

**Issue by drowe** [ankane/groupdate#261]
Referencing issue #256 - in the event the result contains non-unique strings (ie, group_by_day using :format => "%a" for day of the week) - could there be an argument to allow for averaging those grouped by data points?  Such that - given a 3-month period, average counts of X by day of the week (think logistic / production scheduling).

**Comment by ankane** [comment]
Hey @drowe, thanks for the suggestion, but I think additional aggregations are better handled outside of Groupdate.
