### ISSUE TITLE
[Idea] Group by fiscal year

### ISSUE THREAD

**Issue by jonathanloos** [ankane/groupdate#263]
Hey everyone,

First off I would like to say how amazing groupdate has been to use on our platform so thank you from us at [Harled](https://github.com/harled). 

I would like to propose the feature of grouping data by fiscal year as we've had quite a few needs surrounding it.

### Example data:
Given a queryable set:
```ruby
set = [
  {created_at: Jan 2021},
  {created_at: Feb 2021},
  {created_at: Mar 2021},
  {created_at: Apr 2021},
  {created_at: May 2021},
  {created_at: Jun 2021}
]
```

### Example output:
```ruby
# Assumes fiscal year is configured to start in April
# returns something along the lines of: {01 Jan 2021=>3, Sat, 01 Jan 2022=>3}
set.group_by_fiscal_year(:created_at).count
```

Additionally this will likely require the configuration of the "start date of a fiscal year" as it's not the same across the board.

Let me know if you need any other info 🙂

**Comment by ankane** [comment]
Hey @jonathanloos, thanks for the suggestion. Added support in the [year_start](https://github.com/ankane/groupdate/compare/year_start) branch if you want to try it (it outputs the date the year starts rather than Jan 1). Still deciding if it's worth the additional complexity to support.

**Comment by jonathanloos** [comment]
@ankane sorry for the delay, will look at in shortly!

**Comment by Sumit-Gems** [comment]
Hi Gyus, Any update on the feature of group by fiscal year?

As I can see above there is a branch that implement this feature but not yet merge into master.

**Comment by ankane** [comment]
Hi @Sumit-Gems, don't think I want to support the extra complexity at this point.
