### ISSUE TITLE
Group by week: Possible for `week_start` to be the first day in a given range?

### ISSUE THREAD

**Issue by wtholt** [ankane/groupdate#265]
Hi,

Thanks for all your work on this gem. I've enjoyed using it so far. 

I was wondering if there is a way I could have the `week_start` when grouping by week begin with the first day of the given range?

For example:

```
relation = Object.where(created_at: 2022-10-15..2022-11-15)

relation.group_by_week(:created_at).count
```

Right now it defaults to Sunday of a week, so the results would be something like:

```
2022-10-9 => 5,
2022-10-16 => 5,
2022-10-23 => 5,
2022-10-30 => 5
etc.
```

Would it be possible for the gem to be smart enough and begin on the date I requested?

So ideally:

```
2022-10-15=>5,
2022-10-22=>5,
2022-10-29=>5,
2022-11-05=>5
etc
```

Let me know if this is possible right now with the library, I didn't notice this in the documentation or any other issues.

**Comment by ankane** [comment]
Hey @wtholt, you can do something like:

```ruby
range = Date.parse("2022-10-15")..Date.parse("2022-11-15")
week_start = range.begin.strftime("%A").downcase.to_sym
relation.group_by_week(:created_at, week_start: week_start, range: range).count
```
