### ISSUE TITLE
Database missing time zone support for Etc/UTC

### ISSUE THREAD

**Issue by SafeAF** [ankane/groupdate#266]
Getting error:
Database missing time zone support for Etc/UTC - see https://github.com/ankane/groupdate#for-mysql

I read the referenced github issue and:

MariaDB [(none)]> SELECT CONVERT_TZ(NOW(), '+00:00', 'Etc/UTC');
+----------------------------------------+
| CONVERT_TZ(NOW(), '+00:00', 'Etc/UTC') |
+----------------------------------------+
| NULL                                   |
+----------------------------------------+
1 row in set (0.000 sec)

However I ran:
MariaDB [(none)]> SET GLOBAL time_zone = '-7:00';
Query OK, 0 rows affected (0.000 sec)

MariaDB [(none)]> SELECT @@global.time_zone;
+--------------------+
| @@global.time_zone |
+--------------------+
| -07:00             |
+--------------------+
1 row in set (0.000 sec)

What am i missing? Thank you.

**Comment by ankane** [comment]
Hi @SafeAF, check out the Contributing Guide for where to get help.
