### ISSUE TITLE
[Idea] Support for `async` queries?

### ISSUE THREAD

**Issue by Sexual** [ankane/groupdate#269]
Rails 7.1 introduces more async queries such as `async_count` and `async_sum`. Would love to use these with `groupdate`, however it currently raises an error:

```ruby
undefined method 'key?' for #<ActiveRecord::Promise status=complete>
```

I assume this is likely because to actually get the value you have to do `async_count.value`, so wherever `key?` is being run, it should instead be `.value.key?`

**Comment by ankane** [comment]
Support was added in Groupdate 6.2 - make sure you're on the latest version.
