### ISSUE TITLE
Additional .group returns data in unusable format

### ISSUE THREAD

**Issue by sbsurf** [ankane/groupdate#274]
Apologies if this has already been answered, I couldn't find it.

When I do an additional `.group`, like so:

```
Stat.unscoped.group(:operator_id).group_by_day(:created_at).count
```
I get the data in a format that is unexpected:

```
{
 [27, Fri, 03 Feb 2023]=>2,
 [27, Sat, 04 Feb 2023]=>3,
 [28, Sat, 04 Feb 2023]=>1
}
```

I would have expected something usable like:

```
{
 27=>{"Fri, 03 Feb 2023"=>2},
 27=>{"Sat, 04 Feb 2023"=>3},
 28=>{"Sat, 04 Feb 2023"=>1}
}
```

Is there a way to achieve something close to that? In other words, actually group by operator id and then the count per day?

**Comment by ankane** [comment]
Hi @sbsurf, Groupdate tries to match the same format as `group` (replace `group_by_day` with `group` in the query above to see), but you could write a custom method in your application to transform it to the format above.

**Comment by sbsurf** [comment]
OK, thank you. I was trying to avoid looping over a large data set, but you're right, it does follow the existing pattern.
