### ISSUE TITLE
Sometimes group_by_date results are not sorted

### ISSUE THREAD

**Issue by thebravoman** [ankane/groupdate#279]
This is the exact code

```

          render json: [
            { name: :assignments, data: assignments.group_by_day(:created_at).count },
            { name: :assignment_visits, data: assignment_visits.group_by_day(:created_at).count },
            { name: :messages, data: messages.group_by_day(:created_at).count },
            { name: :telegram_chats, data: telegram_chat_records.group_by_day(:created_at).count }
          ]
```
and this is the result

<img width="1185" alt="Screenshot 2024-03-04 at 19 52 51" src="https://github.com/ankane/groupdate/assets/1311493/3e037c5b-33b5-415b-a3a1-4cd982e1e036">

Sometimes the results are not sorted by date and I don't understand why. 
I think it is only here where the json is an array of data.

**Comment by ankane** [comment]
Hi @thebravoman, JSON objects are unordered, so you'll need to convert them to arrays with `to_a` if you want to preserve the order.

**Comment by thebravoman** [comment]
The getting started says another thing @ankane 
https://github.com/ankane/groupdate?tab=readme-ov-file#getting-started

```
Results are returned in ascending order by default, so no need to sort.
```
 
Am I missing something. 

The problem is not that the json is not sorted but that the 
```
assignments.group_by_day(:created_at).count 
```
returns something that is not sorted and the getting started says there is no need to sort.

**Comment by ankane** [comment]
If you can create a minimal reproducible example or test case that shows this, happy to look into it more.
