### ISSUE TITLE
Malformed Year in `group_by_month_of_year`

### ISSUE THREAD

**Issue by chuck-john** [ankane/groupdate#281]
When using `group_by_month_of_year`, an incorrect year value is rendered.

Issue exists in v6.4.0 and `master` branch.

Please see the following repository for a working example. Follow README for steps to reproduce.

https://github.com/chuck-john/groupdate-test

* Ruby 3.2.2
* Rails 7.1
* MariaDB 11.3.2 (via MySQL adapter, time zone support enabled)
* Chartkick 5.0.6
* Groupdate 6.4.0

![bug](https://github.com/ankane/groupdate/assets/1545623/0f273725-0caf-4c5f-b688-609772b8cf92)

**Comment by ankane** [comment]
Hi @chuck-john, check out #185.
