### ISSUE TITLE
ActiveRecord::Base.default_timezone = :utc not working in Rails 7

### ISSUE THREAD

**Issue by ademir10** [ankane/groupdate#284]
Hello!
After to migrate our API to Rails 7 we can't use this method to use the groupdate gem:

ActiveRecord::Base.default_timezone = :utc

   @entradas_bancarias = Fluxo.includes(:banco).where(operador: '+').group('bancos.nome').group_by_day('fluxos.created_at').where("fluxos.created_at::date BETWEEN ? AND ?", params[:date1], params[:date2]).sum(:valor)

ActiveRecord::Base.default_timezone = :local

this is the error message:
undefined method `default_timezone=' for ActiveRecord::Base:Class

Do you know how to fix it, guys? 

Environment:
Rails 7.1.3.4 application starting in development 
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.1.4-p223) ("The Eagle of Durango")
thank you!

**Comment by ankane** [comment]
Hi @ademir10, the option was changed to `ActiveRecord.default_timezone` in Active Record 7+.

**Comment by ademir10** [comment]
thank you so much!
