### ISSUE TITLE
ActiveRecord::Base.default_timezone is deprecated and will be removed in Rails 7.1.

### ISSUE THREAD

**Issue by mactunechy** [ankane/groupdate#285]
ActiveRecord::Base.default_timezone is deprecated and will be removed in Rails 7.1. This means `relation.default_timezone` will fail assuming the `relation` inherits from ActiveRecord::Base

See:
https://github.com/mactunechy/groupdate/blob/93db17384d8f46590af30a60ee2ee4340356fb8e/lib/groupdate/adapters/base_adapter.rb#L21

**Comment by ankane** [comment]
Hi @mactunechy, there's a different code path for Active Record 7+ (see the previous lines).
