### ISSUE TITLE
Rails 8 issue

### ISSUE THREAD

**Issue by HamptonMakes** [ankane/groupdate#287]
I'm upgrading my application to the Rails 8.0.0.beta1 and I'm getting an error from groupdate.

I traced it down to this line: https://github.com/ankane/groupdate/blob/master/lib/groupdate/enumerable.rb#L8

The error that bubbles up from this is...

```Error: the evaluation of `product_variety.fulfillment_order_items.group_by_day(:created_at).instance_variable_get(:@backtrace)` failed with the exception 'undefined method `group_by_period' for nil'```

So, I'm thinking `@klass` must be nil in this instance.

I'll keep investigating, but wanted to open this ticket!

**Comment by ankane** [comment]
Hi @HamptonMakes, this is fixed in the most recent version (#283).

**Comment by HamptonMakes** [comment]
@ankane sorry about that! I read through the issues and PRs and didn't see anything!

Thanks for this great library and all that you share with us! <3
