### ISSUE TITLE
Inconsistent behavior with day_start and week_start

### ISSUE THREAD

**Issue by ankane** [ankane/groupdate#33]
`day_start` changes `group_by_hour_of_day`, but `week_start` does not change `group_by_day_of_week`.

Need to decide on the proper behavior and make this consistent.

**Comment by ankane** [comment]
My gut says `day_start` shouldn't change `hour_of_day`. Since this isn't backwards compatible, will need to add it as an option, and wait for Groupdate 4.0 to make it the default.

**Comment by leonelgalan** [comment]
@ankane, I'm ready to help. I'm with your gut feeling. `day_start` shouldn't change `hour_of_day` and back to my original issue, `week_start` should affect `day_of_week`. I'll work on test cases for those assumptions, show and tell and we can discuss the change, deprecation warnings if needed and all that later.

**Comment by ankane** [comment]
Fixed in Groupdate 4
