### ISSUE TITLE
Scoping time_range

### ISSUE THREAD

**Issue by kakoni** [ankane/groupdate#38]
So this new time_range scoping (with all the dates in the series)

```
User.group_by_day(:created_at, range: 2.weeks.ago.midnight..Time.now).count
```

works really nice. 

Wonder if there is a possibility to make ranges somehow work with scopes? I mean something like this instead;

```
User.for_given_range(2.weeks.ago.midnight..Time.now).group_by_day(:created_at).count
```

?
Would be lot easier to use this from controller (and has_scope gem)

**Comment by wmantegna** [comment]
Any progress on this? I'd love to see this functionality as well.

**Comment by ankane** [comment]
Cleaning up old issues. I don't see a strong reason to add this right now.
