### ISSUE TITLE
Is it possible to get grouped sums of a method result that is not a table column?

### ISSUE THREAD

**Issue by michaelfeihstel** [ankane/groupdate#49]
I'm aware that this might not be an issue that is related to this gem, but a more general question regarding Rails. Nevertheless I thought this might still be a good place to ask.

Let's assume I have a query like this:

```
LineItem.group_by_month(:created_at).sum("quantity")
```

That works as expected. However we have a special case of LineItems that require additional calculations to get a total_quantity, like

```
def total_quantity
    value1 + value2 + value3
end
```

I'd like to use a query like

```
LineItem.group_by_month(:created_at).sum(&:total_quantity)
```

Unfortunately this returns a PG:GroupingError that tells me the query expects that "column "line_items.id" must appear in the GROUP BY clause or be used in an aggregate function", which is probably necessary for a valid SQL query, but the problem remains:

Is there an elegant way to aggregate the total_quantity, or in general the result of a method, in a groupdate query?

**Comment by RigoTheCEO** [comment]
Been searching for this all day. Thank you.
