### ISSUE TITLE
Add support for MongoDB?

### ISSUE THREAD

**Issue by ankane** [ankane/groupdate#5]
MongoDB only supports two time zones (UTC and local time), but it's possible to group by hour in the database and aggregate the results in Ruby.

This works for:
- count
- sum
- minimum
- maximum

But not for:
- average
- time zones with a partial hour offset

Let me know if this is useful.

**Comment by sman591** [comment]
+1

**Comment by chr1s1** [comment]
+1

**Comment by dmitrypol** [comment]
+1

**Comment by Startouf** [comment]
+1 any news ?

**Comment by ankane** [comment]
If someone wants to submit a PR \*and\* help support it going forward (fix bugs within a week, respond to issues, etc), we can give this a shot, even without full time zone support.

**Comment by ankane** [comment]
Going to close this, but happy to review a PR for it.
