### ISSUE TITLE
Groupdate.day_start should be a Time object OR provide support for time_offset

### ISSUE THREAD

**Issue by jufemaiz** [ankane/groupdate#50]
For example:

```
2.hours
30.minutes
```

etc

or alternatively provide support for a Groupdate.time_offset allowing for shifting of time values.

The use case is where a user wishes to group accumulated data that falls on whole minutes. At whole hours (for example) this data would currently shift into the next hour (or day or week, or month), but it is data representing the aggregation of the previous x minutes.

If grouping by date, for example, with 30 minute reporting data, the 00:00 value is for the previous day.

**Comment by ankane** [comment]
Cleaning up old issues
