### ISSUE TITLE
How to handle ambiguous column name?

### ISSUE THREAD

**Issue by cmalpeli** [ankane/groupdate#51]

**Comment by thirdsun** [comment]
@cmalpeli Could you share your solution if you ever found one? I'm dealing with the same problem since I'm trying to use Groupdate on a `has_many ... through: ...` - relation on both involved tables use columns that share a name

**Comment by ankane** [comment]
@thirdsun You can do:

```ruby
Visit.joins(:user).group_by_day("users.created_at").count
```

**Comment by thirdsun** [comment]
Yes, I tried that...turns out I forgot to `reload!` in the console while I tried those queries. It's all good now.

Thanks!
