### ISSUE TITLE
All 'day' values are null

### ISSUE THREAD

**Issue by sdhull** [ankane/groupdate#56]
I've been trying to use this awesome sounding library all afternoon, to no avail.

When using it in console, it returns `nil`, with a warning:

```
RuntimeError: Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql
from /Users/stevehull/.rvm/gems/ruby-1.9.3-p448/gems/groupdate-2.2.1/lib/groupdate/magic.rb:119:in `rescue in perform'
```

I followed the recommendation and loaded the timezones.  They didn't all load, but the `'America/Los_Angeles'` zone loaded just fine so I figure I'm good to go.

Here's the query it constructed:

```
SELECT COUNT(*) AS count_all, DATE_ADD(CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(`created_at`, INTERVAL 0 HOUR), '+00:00', 'America/Los_Angeles'), '%Y-%m-%d 00:00:00'), 'America/Los_Angeles', '+00:00'), INTERVAL 0 HOUR) AS day FROM `listing_invites` WHERE (`created_at` IS NOT NULL) GROUP BY DATE_ADD(CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(`created_at`, INTERVAL 0 HOUR), '+00:00', 'America/Los_Angeles'), '%Y-%m-%d 00:00:00'), 'America/Los_Angeles', '+00:00'), INTERVAL 0 HOUR);
```

And there results it returned:

```
count_all   day
20  NULL
```

And when I try a simple `CONVERT_TZ` myself:

```
select convert_tz(created_at, '+00:00', 'America/Los_Angeles') from listing_invites;
```

It works fine.

Strange turning to bizarre... if I add some returns in the constructed query above, it runs fine:

```
SELECT
  COUNT(*) AS count_all,
  DATE_ADD(CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(`created_at`, INTERVAL 0 HOUR), '+00:00', 'America/Los_Angeles'), '%Y-%m-%d 00:00:00'), 'America/Los_Angeles', '+00:00'), INTERVAL 0 HOUR) AS day
FROM `listing_invites`
WHERE (`created_at` IS NOT NULL)
GROUP BY DATE_ADD(CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(`created_at`, INTERVAL 0 HOUR), '+00:00', 'America/Los_Angeles'), '%Y-%m-%d 00:00:00'), 'America/Los_Angeles', '+00:00'), INTERVAL 0 HOUR);
```

And it returns:

```
count_all   day
2   2014-04-17 07:00:00
2   2014-04-18 07:00:00
1   2014-04-22 07:00:00
1   2014-04-28 07:00:00
14  2014-05-27 07:00:00
```

.....

![wat](http://codropspz.tympanus.netdna-cdn.com/codrops/wp-content/uploads/2013/07/wat.jpg)

**Comment by jdguzman** [comment]
I'm having this issue too trying to use the gem.  I have added timezone support on the mysql server and when I run the app I get the "install time zone support" error, which I already have.

https://gist.github.com/cab57e726e0780ca8f7f.git

The gist above shows that the error also happens in the console.  But if I try to run the same query using `connection.execute` it seems to work fine.

Any ideas?

**Comment by villins** [comment]
@jdguzman look at this https://github.com/ankane/groupdate#for-mysql

**Comment by jdguzman** [comment]
@villins I have already done that.
