### ISSUE TITLE
get around mysql_tzinfo_to_sql

### ISSUE THREAD

**Issue by huchenme** [ankane/groupdate#58]
Hi,

I don't have permission to change mysql table in RDS instance. Is there any way to get around mysql_tzinfo_to_sql? or even get around time zone is acceptable. I get stuck here for few days.

Thanks

**Comment by ingmaras** [comment]
If I'm not mistaken, all that's needed to make this work (and even still retain timezone support) is the ability to override the value of time_zone in Groupdate::Magic#relation.

On a MySQL server without Timezone support, CONVERT_TZ(DATE_SUB(FROM_UNIXTIME(ts), INTERVAL 0 HOUR), '+00:00', 'Europe/Amsterdam') returns NULL. However, if you change 'Europe/Amsterdam' to '+01:00', it works fine.

**Comment by ankane** [comment]
Unfortunately, it's not that easy.  Time zones are dynamic, so `Europe/Amsterdam` will be both `+01:00` and `+02:00` for part of the year.

**Comment by jordanell** [comment]
@huchenme did you ever come up with a solution for this?

**Comment by huchenme** [comment]
@jordanell unfortunately no
