### ISSUE TITLE
PG::Error: ERROR:  column "<table>.created_at" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by tehviking** [ankane/groupdate#6]
In Rails 3.1.10, on Postgres 9.1.2, if I run this:

```
Drop.group_by_day(:created_at).count
```

I get this error:

```
ActiveRecord::StatementInvalid: PG::Error: ERROR:  column "drops.created_at" must appear in the GROUP BY clause or be used in an aggregate function
```

Not sure what could be causing this, but currently trying to update rails to see if that could be related.

EDIT:
I saw that someone else was having this issue but they weren't including an operation, though I am.
I've since upgraded to Rails 3.2.13 and am having the same issue.

**Comment by Preen** [comment]
Yeah, this should be in the Readme, right below the first example. I was freaking out =)

**Comment by cseelus** [comment]
Had the same problem, @Preen's suggestion doesn't sound too bad ;-)
