### ISSUE TITLE
Select multiple aggregate results?

### ISSUE THREAD

**Issue by thedarkside** [ankane/groupdate#61]
Hi,

is it possible to get results like this:
```ruby
{ Mon, 01 Dec 2008 00:00:00 UTC +00:00=>[6,1],
 Thu, 01 Jan 2009 00:00:00 UTC +00:00=>[5,22],
 Mon, 01 Dec 2008 00:00:00 UTC +00:00=>[2,8],
 Thu, 01 Jan 2009 00:00:00 UTC +00:00=>[9,12]
}
```
Ignore the date grouping, it could be by day or month or anything else.

I want to select the `count` **and** the `sum` of a colum in just one query (see array result values). 

How can i accomplish this?

Best regards,
Thedarkside

**Comment by codesnik** [comment]
@thedarkside I've made a gem (https://github.com/codesnik/calculate-all) to calculate count and sum and all the other aggregate functions in one pass.  
It won't work with groupdate right now, but this is my nearest objective.
