### ISSUE TITLE
Connection adapter not supported: SQLite

### ISSUE THREAD

**Issue by vabalasu** [ankane/groupdate#62]
I installed groupdate (and chartkick) today, following the ActiveAdmin example here, but changing the model to an application-specific one that wanted graphed: http://www.patrickedelman.com/simple-charting-for-activeadmin/

That seemed to work fine. The page showed up, and it was filled with a very pretty line graph.

When I tried moving the code into the ActiveAdmin dashboard page (dashboard.rb), I got "Connection adapter not supported: SQLite" errors every time I tried to render it. And now I get those errors on the original example page as well!

I'm not sure if this is a groupdate problem, or some kind of configuration state problem on my end. But I'd appreciate any advice!

**Comment by jsanders67** [comment]
+1 for merging
