### ISSUE TITLE
Is it possible to use .group_by_hour_of_day with a time range?

### ISSUE THREAD

**Issue by dugjason** [ankane/groupdate#69]
I'm using group_by_hour_of_day to show how often an event occurs during business hours (09:00 - 18:00); I'd like to find a way to show the entire series (great feature!) for just a given timeframe, otherwise I always end up with half the graph being empty 100% of the time:

![screen shot 2014-11-25 at 15 04 54](https://cloud.githubusercontent.com/assets/273718/5185106/70dc4f22-74b4-11e4-9f8b-0b4d835f2db6.png)

If I choose to not use the entire series, then you can see that any hours in my time 09:00 - 18:00 time range without any occurrences of the event will not appear (you can see that 14:00 has disappeared):

![screen shot 2014-11-25 at 15 06 23](https://cloud.githubusercontent.com/assets/273718/5185132/b213d140-74b4-11e4-8fb1-8fbb73be00b9.png)

So, does anyone know how I can present just the timeframe from 09:00 - 18:00, but still show the entire series for this period?

**Comment by ankane** [comment]
Hey @dugjason, you'll need to filter out the ends manually for this.
