### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by sonnyparlin** [ankane/groupdate#70]
First time trying to use...

Rack::Shell v1.0.0 started in development environment.
>> User.group_by_day(:created_at).order("day desc").count
TypeError: no implicit conversion of Symbol into Integer
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/gems/groupdate-2.3.0/lib/groupdate/magic.rb:140:in `[]'
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/gems/groupdate-2.3.0/lib/groupdate/magic.rb:140:in `time_zone'
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/gems/groupdate-2.3.0/lib/groupdate/magic.rb:9:in `initialize'
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/gems/groupdate-2.3.0/lib/groupdate/enumerable.rb:5:in `new'
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/gems/groupdate-2.3.0/lib/groupdate/enumerable.rb:5:in `block (2 levels) in <module:Enumerable>'
	from (irb):1
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/gems/racksh-1.0.0/bin/racksh:21:in `<top (required)>'
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/bin/racksh:23:in `load'
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/bin/racksh:23:in `<main>'
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sonnyparlin/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ignazioc** [comment]
same for me.
Sinatra project with DataMapper.
````
irb(main):005:0> User.group_by_day(:created_at).count
TypeError: no implicit conversion of Symbol into Integer
	from /Library/Ruby/Gems/2.0.0/gems/groupdate-2.4.0/lib/groupdate/magic.rb:150:in `[]'
	from /Library/Ruby/Gems/2.0.0/gems/groupdate-2.4.0/lib/groupdate/magic.rb:150:in `time_zone'
	from /Library/Ruby/Gems/2.0.0/gems/groupdate-2.4.0/lib/groupdate/magic.rb:11:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/groupdate-2.4.0/lib/groupdate/enumerable.rb:5:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/groupdate-2.4.0/lib/groupdate/enumerable.rb:5:in `block (2 levels) in <module:Enumerable>'
	from (irb):5
	from /usr/bin/irb:12:in `<main>'

````

The User class is a datamapper class and the "created_at"  attribute is present.
````
irb(main):009:0> User.first[:created_at]
=> Wed, 31 Dec 2014 12:44:07 +0100
`````

any sudgestion?

**Comment by ankane** [comment]
Groupdate only works with ActiveRecord at the moment.

**Comment by ignazioc** [comment]
:( 
maybe you should specify on the Readme?
Is it possible to create some kind of adapter because i don't think you really need ActiveRecord, i suppose you work with an array of Model Object.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by archonic** [comment]
Don't want to revive a closed issue, but I have this exact issue and the readme now says it works with arrays and hashes.

I'm trying to use groupdate with [Logidze](https://github.com/palkan/logidze) to create a sensible revision history feature. Logidze stores all model revisions into a `log_data` jsonb column. I've created a simple DocumentVersion class to create the revision history navigation with groupdate:

```
class DocumentVersion
    attr_accessor :version, :timestamp

    def initialize(attributes = {})
      @version = attributes[:version]
      @timestamp = attributes[:timestamp]
    end
  end
```

I should be able to do something like this:

```
log_data.data["h"].map{ |x|
      DocumentVersion.new(
        version: x["v"],
        timestamp: Time.zone.at(x["ts"] / 1000.0)
      )
    }.group_by_day(
      :timestamp,
      series: false
    ) { |x|
      [
        x.version,
        x.timestamp
      ]
    }
```
But this gets `TypeError: no implicit conversion of Symbol into Hash from /usr/local/bundle/gems/groupdate-4.0.1/lib/groupdate/magic.rb:56:in `group_by'`.

I'm curious what form the arrays in the example would have to have in order to work.
