### ISSUE TITLE
Ending with scope or class method to perform calculation gives strange results

### ISSUE THREAD

**Issue by kreintjes** [ankane/groupdate#73]
I have a strange problem when using groupdate and ending the relation with a scope or class method containing the calculation (e.g. count) call. Suppose I have the following class:

```
class Item < ActiveRecord::Base
  scope :count_scope, -> do
    count
  end

  def self.count_class_method
    count
  end
end
```

When I call `Item.group_by_day(:created_at).count` everything works great, I get a hash with Time objects as keys mapping to integers. However, when I call `Item.group_by_day(:created_at).count_class_method` or `Item.group_by_day(:created_at).count_scope`, I suddenly get a `Groupdate::Series` object instead of an Hash. I seem to be able to extract the results from this by calling `.relation` on this object (e.g. `Item.group_by_day(:created_at).count_class_method.relation`), but I doubt this is the preferred way. Also, when specifying a format for the Hash keys, it seems to be ignored (e.g. when doing `Item.group_by_day(:created_at, format: '%a %e %b').count_class_method.relation).

Of course the count method is only an example. My real calculation class method is somewhat more complex and also used by other parts of my application, hence I prefer not to repeat this code.

Any help with this problem would be greatly appreciated.

**Comment by zorab47** [comment]
I'm seeing the same issue.

**Comment by zorab47** [comment]
Digging into the issue a bit more...

When the branching occurs in [`Groupdate::Series#method_missing`](https://github.com/ankane/groupdate/blob/631621617fe63fa6b26eeca285e186b19c873442/lib/groupdate/series.rb#L16) it returns the `Groupdate::Series` object directly. That does not match the behavior of [`Groupdate::Magic#series`](https://github.com/ankane/groupdate/blob/631621617fe63fa6b26eeca285e186b19c873442/lib/groupdate/magic.rb#L264), which returns the series as a Hash.

**Comment by ankane** [comment]
Added a failing test case on the [count_method branch](https://github.com/ankane/groupdate/tree/count_method). Will try to fix when I have some time.

**Comment by zorab47** [comment]
More information on the behavior. 

`Groupdate::Series` object needs to be returned to handle additional chaining of methods (e.g. `reverse_order`, `order`, `group`, `group_by_*`). The difficulty will be detecting the end of the chain, normally an aggregate method like `count` or other `ActiveRecord::Calculations` methods.

**Comment by ankane** [comment]
Yeah, I'm not sure there's an easy way to do this.

**Comment by zorab47** [comment]
Maybe a new method could be introduced that would indicate the end of the chain?

```ruby
class Post < ActiveRecord::Base
  def self.my_custom_count
    count
  end
end

Post.group_by_month(:date).with_calculation.my_custom_count
                         # ^^^^^^^^^^^^^^^^ "with_calculation" would be an example
```

Other ideas for possible "chain ending" method names:

- `with_calculation`
- `using` (possible conflict with the keyword)

**Comment by zorab47** [comment]
A few more brainstorming ideas...

Add a higher level method to unwrap the chaining:

```ruby
Groupdate.unwrap(Post.group_by_month(:date)).my_custom_count
```

Or take a block to send messages directly to the underlying relation:

```ruby
Post.group_by_month(:date).using { |relation| relation.my_custom_count }
```

Or perform the grouping in a block to signal the chaining is complete

```ruby
Post.group_by { |by| by.month(:date) }.my_custom_count
```

**Comment by ankane** [comment]
Thanks @zorab47, thanks for the ideas.  I'm not sure any will be easy to implement with the way Groupdate works from my initial experimentation (but maybe someone smarter can figure it out).

Another approach would be to have a method on the class that specifies which methods end the chain.  It doesn't feel super clean (I'm not sure any of the approaches do), but should be fairly simple to implement in `Groupdate::Series`.

```ruby
class Post 
  def self.groupdate_calculation_methods
    [:my_count_count]
  end
end
```

Thoughts?

**Comment by zorab47** [comment]
That idea works and reminds me of how [Ransack](https://github.com/activerecord-hackery/ransack) whitelists its custom search methods.

**Comment by zorab47** [comment]
I plan on implementing the solution you proposed below soon. Anything else to add/discuss before I begin?

```ruby
class Post 
  def self.groupdate_calculation_methods
    [:my_count_count]
  end
end
```

**Comment by ankane** [comment]
No, let's do it 👍
