### ISSUE TITLE
No way to disable timezone

### ISSUE THREAD

**Issue by talha-asad** [ankane/groupdate#74]
Pretty neat gem, however it lacks the functionality to disable timezone support. What if someone just wanted to use the server time to group?

**Comment by mbrookes** [comment]
> What if someone just wanted to use the server time to group?
Then they would probably use [Dateslices](https://github.com/HappyFunCorp/dateslices)

**Comment by fenelon** [comment]
@ankane, we're using MySQL on Amazon RDS and they have out-of-date timezones that they won't allow to change. This causes issues with grouping using your gem as it is relying on time zones. I'm not sure if there is a neat way to fix this, but maybe you have in mind some way of overcoming this issue? I've attached a screenshot, that demonstrates an issue on my development machine (left) and on RDS (right). Thanks a lot!

<img width="1291" alt="screenshot 2016-02-11 21 37 41" src="https://cloud.githubusercontent.com/assets/767838/12990600/4c5d02de-d11c-11e5-9b6e-f04b23a7b07f.png">

**Comment by ankane** [comment]
Cleaning up issues.

@fenelon Nothing comes to mind - just have to waiting until Amazon fixes it.
