### ISSUE TITLE
Possible to do aggregated sums vs counts?

### ISSUE THREAD

**Issue by i8ramin** [ankane/groupdate#75]
Given counts as below..

User.group_by_day(:created_at).count
```
# {
#   2013-04-16 00:00:00 UTC => 50,
#   2013-04-17 00:00:00 UTC => 100,
#   2013-04-18 00:00:00 UTC => 34
# }
```

Would be great if "sum" returned the following

```
User.group_by_day(:created_at).sum
# {
#   2013-04-16 00:00:00 UTC => 50,
#   2013-04-17 00:00:00 UTC => 150,
#   2013-04-18 00:00:00 UTC => 184
# }
```

To plot a graph with the counts and aggregated sum of the counts:

```
<%= line_chart [
  { name: 'counts', data: User.group_by_day(:created_at).count },
  { name: 'sum', data: User.group_by_day(:created_at).sum }
] %>
```

Is this possible? Thanks

**Comment by zackperdue** [comment]
Yes it is possible, just do
```
User.group_by_day(:created_at).sum(:column_to_sum)
```

**Comment by egoens** [comment]
AH. Thanks @zackperdue. I missed this too. Very helpful!

**Comment by zackperdue** [comment]
Welcome @egoens!

**Comment by thirdsun** [comment]
Quick follow up question: How would this work if `:column_to_sum` isn't an actual table column but a method. I tried `.sum(&:method_name)` but it wouldn't work.

Also, I assume my approach would use Ruby sum method. Preferably I'd like to have the calculation done by the database though, which should be the fastest approach. That may be out of the scope of this gem, but is there any chance it could help with that?

**Comment by zackperdue** [comment]
I'm not exactly sure how the gem is working. Try something like this?
```
class ScoreBoard < ActiveRecord::Base
  def column_to_sum
    42
  end
...
```

**Comment by thirdsun** [comment]
Thanks @zackperdue - I edited my question. Turns out I had the very same problem before and it has already been answered.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by skensell** [comment]
How was this issue marked closed?  The original question did not get answered.  Notice that the questioner (as do I) wants to know how to sum the counts output.  Do you have to manually iterate over the counts output and sum it? I would expect built-in support for this.

**Comment by skensell** [comment]
Here is my solution:

```Ruby
User.group_by_month(:created_at, range: 1.year.ago..Time.now).count.inject(Hash.new(0)) { |acc, (k,v)| acc[:total] += v; acc[k] = acc[:total]; acc }.except(:total)
```

**Comment by RailsCod3rFuture** [comment]
> Here is my solution:
> 
> ```ruby
> User.group_by_day(:created_at).count.inject(Hash.new(0)) { |acc, (k,v)| acc[:total] += v; acc[k] = acc[:total]; acc }.except(:total)
> ```

The issue I am having with your your approach, is nothing shows on the graph. The count remains zero. Am I doing something wrong??

My original method is this: current_user.posts.sum(&impressionist_count).group_by_day(:created_at).count. What I would like to do is graph the impressions sum for each day/month/year in total.

**Comment by duleorlovic** [comment]
Similar solution
```
# input: { "2020-01-01": 3, "2020-01-02": 1, "2020-01-03": 5 }
# output: { "2020-01-01": 3, "2020-01-02": 4, "2020-01-03": 9 }
def accumulate(data)
  total = 0
  data.each_with_object({}) do |(date, count), acc|
    total += count
    acc[date] = total
  end
end
```
To use you need to call on final data like
```
accumulate User.group_by_day(:created_at).count
```
