### ISSUE TITLE
Feature request: common grouping method - groupdate_by(kind, ...)

### ISSUE THREAD

**Issue by zuf** [ankane/groupdate#80]
Sometimes users need to have ability to manually choose grouping period.
In this case we can create form with select field with common options (by_day, by_week, by_month, ...etc).
So, it will be very nice if groupdate provides common method to group by date.

Examples:

```ruby
User.groupdate_by(:day, :created_at).count
Task.groupdate_by(:month, :created_at).count
```

**Comment by ankane** [comment]
@zuf you can do:

```ruby
User.send("group_by_#{period}", :created_at).count
```

**Comment by zuf** [comment]
Yep. Actually now I have used "scope wrapper" which selects given period. But all of this kind of solutions doesn't looks elegant in model/controller code.

So, if you think this is an unnecessary feature - just close this issue.

**Comment by ankane** [comment]
I like the idea.  How about:

```ruby
User.group_by_period(params[:period], :created_at, permit: %w[day week]).count
```

With `permit` optional?

**Comment by zuf** [comment]
This would be nice.

**Comment by ankane** [comment]
Added on the `dynamic_grouping` branch.  However, not happy with the name `group_by_period` since some of the methods like `hour_of_day` aren't periods.  Other ideas are `group_by_bucket` and `group_by_method` but those aren't great either.

**Comment by zuf** [comment]
I agree. Some method name candidates: `group_by_interval`, `group_by_time_span`, `group_by_span`, `group_by_time`

**Comment by ankane** [comment]
Still not in love with it, but going with `group_by_period` for now.  Merged to master :)  Thanks for the suggestion!
