### ISSUE TITLE
Adding series option to group_by_* overrides format option

### ISSUE THREAD

**Issue by edwardloveall** [ankane/groupdate#82]
I have a query like:

```ruby
Activity.group_by_day(:created_at, format: "%m/%e/%Y").count
```

which returns:

```ruby
{
  "05/05/2015"=>1,
  "05/06/2015"=>0,
  "05/07/2015"=>0,
  "05/08/2015"=>0,
  "05/09/2015"=>0,
  "05/10/2015"=>0,
  "05/11/2015"=>0,
  "05/12/2015"=>0,
  "05/13/2015"=>7,
  "05/14/2015"=>2
}
```

When I add the `series: false` option, it returns this:

```ruby
Activity.group_by_day(:created_at, format: "%m/%e/%Y", series: false).count

{
  "2015-05-05 00:00:00 UTC"=>1,
  "2015-05-13 00:00:00 UTC"=>7,
  "2015-05-14 00:00:00 UTC"=>2
}
```

I'm faking some data here to show the issue as my real query isn't as helpful to explain the problem, but this is equivalent the result I get.

**Comment by jjgreen** [comment]
This bites me too, easy enough to filter out the zeros, but gnarly

**Comment by ankane** [comment]
This is fixed in Groupdate 3.0+.

**Comment by jjgreen** [comment]
I'm using 3.0 and still seeing the same problem

**Comment by jjgreen** [comment]
Fix confirmed, many thanks!
