### ISSUE TITLE
Stub empty dates with zeros

### ISSUE THREAD

**Issue by caseypugh** [ankane/groupdate#84]
If I wanted to show all user signups in the last 30 days (by day), and let's say the most recent 5 days are all zero, it'd be great to optionally stub in those 5 days with zeros. Right now it will return nothing. This would be helpful so I can more easily create accurate graphing tools. 

Perhaps this exists already? Here's an example that uses time series to solve the problem: http://crossingtheruby.com/2013/12/15/time-series-with-postgresql.html

**Comment by ankane** [comment]
Hey Casey, Groupdate will fill in zeros if you use the `range` or `last` options.

```ruby
User.group_by_day(:created_at, last: 30).count
```

**Comment by caseypugh** [comment]
Ahh, thank you! I spent way too long researching alternatives. :smile:

**Comment by stevo2105** [comment]
saved my life
