### ISSUE TITLE
group_by_hour(:created_at, time_zone: 'London') and summer time

### ISSUE THREAD

**Issue by tigus** [ankane/groupdate#90]
Hello,

```
Order.group_by_hour(:updated_at, time_zone: 'London').count
```

I got trouble when i try to execute this command. Normally all is ok but since this week end with the hour change i got trouble when i put time_zone in the query. The command freeze...

Any idea?

**Comment by ankane** [comment]
Hi @tigus, can you see if it still freezes on the latest version?

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen with more info.

**Comment by tigus** [comment]
i did'nt test during last summer time change. Next time may be.

Tx for update !
