### ISSUE TITLE
Count other model def

### ISSUE THREAD

**Issue by dogmagames** [ankane/groupdate#93]
Is it possible to the 'count' number utilize the data from a model method?
Eg:
<%= line_chart Bet.group_by_day(:created_at).total_dolar %>

**Comment by ankane** [comment]
You can use other [ActiveRecord calculation methods](http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html) like `sum` and `average`.

**Comment by ankane** [comment]
Cleaning up issues
