### ISSUE TITLE
Include 0 counts in series

### ISSUE THREAD

**Issue by Carpela** [ankane/groupdate#96]
Is there a way to include 0 counts in a series. 

e.g. 
Thing.group_by_week(:created_at, include_zero:true).count
=>
{
"01/01/2015" => 17,
"08/01/2015" => 0,
"15/01/2015" =>23
}

Is this what "Entire Series" means, and am I missing something obvious?

**Comment by Carpela** [comment]
Ok. Found it in the code. 
Adding default_value:true fixes it. Is that supposed to happen by default anyway? 
Not working for me on v2.5

**Comment by Carpela** [comment]
Not sure this will work actually, default_value:true picks up items in the gaps, but won't set a value for the any before the earliest count or after the latest count.

**Comment by embs** [comment]
Did you check out #84?

**Comment by ankane** [comment]
Cleaning up issues
