### ISSUE TITLE
Incompatible with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by airblade** [ankane/groupdate#99]
I upgraded MySQL from 5.5 to 5.7 and immediately encountered this exception (edited for legibility):

```
Mysql2::Error: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'stories.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by:

SELECT COUNT(*) AS count_all, DATE_ADD(CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(`stories`.`create
d_at`, INTERVAL 0 HOUR), '+00:00', 'Europe/Berlin'), '%Y-%m-01 00:00:00'), 'Europe/Berlin', '+00:00'), INTERVAL 0 HOUR) AS month FROM `stories` 
WHERE (`stories`.`created_at` >= '2013-04-15 12:48:36' AND `stories`.`created_at` <= '2014-01-22 16:04:33')
GROUP BY DATE_ADD(CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(`stories`.`created_at`, INTERVAL 0 HOUR), '+00:
00', 'Europe/Berlin'), '%Y-%m-01 00:00:00'), 'Europe/Berlin', '+00:00'), INTERVAL 0 HOUR) 
ORDER BY stories.id
```

This is the code in question:

```ruby
stories.group_by_month('created_at', range: range).count
```

It turns out that MySQL 5.5 doesn't set its `sql_mode` to anything, which you can verify with `select @@sql_mode;` on the MySQL command line.  However MySQL 5.7 sets it to `ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`.

In this case I didn't care about the order of the results, because they are aggregated, so I made the problem go away by adding this to `config/environment.rb`:

```ruby
# Set MySQL to clear sql mode for all connections
# http://stackoverflow.com/a/21615180/151007
class ActiveRecord::ConnectionAdapters::Mysql2Adapter 
  alias :connect_no_sql_mode :connect
  def connect
    connect_no_sql_mode
    execute("SET sql_mode = ''")
  end
end

ActiveRecord::Base.connection.reconnect!
```

I'm using groupdate 2.2.1 and Rails 3.0.20.

I thought I'd mention it here in case anyone else runs into it.

**Comment by ankane** [comment]
Do you have `default_scope` on your `Story` model, or anything else that would be ordering the results by id?

**Comment by airblade** [comment]
Yes, the `stories` in `stories.group_by_month...` is a call to a method which loads some stories and reorders by id.

**Comment by ankane** [comment]
Another solution to the problem is getting rid of the order in the group call.

```ruby
stories.reorder(nil).group_by_month('created_at', range: range).count
```

**Comment by airblade** [comment]
That sounds like a better solution.  Thanks!
